import hre from "hardhat";
const { ethers } = hre as any;
import fs from "fs";
import path from "path";
import crypto from "crypto";

const ROOT = path.join(__dirname, "../..");
const MANAGED_ROLES = [
  "DEFAULT_ADMIN_ROLE", "PROTOCOL_ADMIN_ROLE", "OPERATOR_ROLE", "REVIEWER_MANAGER_ROLE", "TREASURY_ROLE", "PAUSER_ROLE", "VAULT_MANAGER_ROLE",
];
const AGIALPHA = "AGIALPHA";
const ERC173 = "0x7f5828d0";

function sha256(buf: Buffer | string) { return "0x" + crypto.createHash("sha256").update(buf).digest("hex"); }
function writeJsonAtomic(file: string, data: any) { fs.mkdirSync(path.dirname(file), { recursive: true }); const tmp = `${file}.tmp-${process.pid}`; fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + "\n"); fs.renameSync(tmp, file); fs.writeFileSync(`${file}.sha256`, sha256(fs.readFileSync(file)) + "  " + path.basename(file) + "\n"); }
function requireAddress(name: string) { const v = process.env[name]; if (!v || !ethers.isAddress(v) || ethers.getAddress(v) === ethers.ZeroAddress) throw new Error(`Missing/invalid ${name}`); return ethers.getAddress(v); }
function forbidCiMainnet(chainId: bigint) { if (chainId === 1n && (process.env.CI || process.env.GITHUB_ACTIONS)) throw new Error("Mainnet ownership handoff is local-only and forbidden in CI/GitHub Actions"); }
function manifestPath(label: string) { return path.join(ROOT, "deployments", `${label}.agialpha.latest.json`); }
function latestPlanPath(label: string) { return path.join(ROOT, ".private", `${label}.ownership-plan.latest.json`); }
function publicHandoffPath(label: string) { return path.join(ROOT, "deployments", `${label}.ownership-handoff.latest.json`); }
function evidencePath(label: string) { return path.join(ROOT, "qa", `${label.replace("ethereum-", "")}-ownership-handoff-evidence.json`); }
function reportPath(label: string) { return path.join(ROOT, "docs", label === "ethereum-mainnet" ? "ETHEREUM_MAINNET_OWNERSHIP_HANDOFF_REPORT.md" : "SEPOLIA_OWNERSHIP_HANDOFF_REPORT.md"); }
function readManifest(label: string) { const p = manifestPath(label); if (!fs.existsSync(p)) throw new Error(`Missing deployment manifest ${p}`); const raw = fs.readFileSync(p); return { path: p, hash: sha256(raw), data: JSON.parse(raw.toString("utf8")) }; }
function entries(manifest: any) { const c = manifest.contracts || manifest.addresses || {}; return Object.entries(c).filter(([name, value]) => name !== AGIALPHA && typeof (value as any) === "string" && ethers.isAddress(value as string)).map(([name, address]) => ({ name, address: ethers.getAddress(address as string) })).sort((a,b)=>a.name.localeCompare(b.name)); }
async function contractAt(address: string) { return new ethers.Contract(address, ["function owner() view returns (address)", "function transferOwnership(address)", "function supportsInterface(bytes4) view returns (bool)", "function hasRole(bytes32,address) view returns (bool)", ...MANAGED_ROLES.map(r=>`function ${r}() view returns (bytes32)`), "function managedOwnershipRoleCount() view returns (uint256)", "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)", "event GoalOSOwnershipRolesMigrated(address indexed previousOwner,address indexed newOwner)"], ethers.provider); }
async function roleIds(c: any) { const out: any = {}; for (const r of MANAGED_ROLES) out[r] = await c[r](); return out; }
async function validateProof(label: string, chainId: bigint, finalOwner: string, manifestHash: string) { if (chainId !== 1n) return { required: false }; const p = process.env.FINAL_OWNER_CONTROL_PROOF_PATH || ".private/final-owner-control-proof.json"; if (!fs.existsSync(path.join(ROOT,p))) throw new Error(`Missing Mainnet final-owner control proof ${p}`); const proof = JSON.parse(fs.readFileSync(path.join(ROOT,p),"utf8")); if (ethers.getAddress(proof.finalOwnerAddress) !== finalOwner || BigInt(proof.chainId) !== chainId || proof.deploymentManifestSha256 !== manifestHash) throw new Error("Final-owner proof target/chain/manifest mismatch"); if (Date.parse(proof.expiresAt) <= Date.now()) throw new Error("Final-owner proof expired"); return { required: true, commitment: sha256(JSON.stringify(proof)) };
}
async function doctor(label: string) { const net = await ethers.provider.getNetwork(); forbidCiMainnet(net.chainId); const finalOwner = requireAddress("FINAL_OWNER_ADDRESS"); const [deployer] = await ethers.getSigners(); if (ethers.getAddress(deployer.address) === finalOwner) throw new Error("FINAL_OWNER_ADDRESS must differ from disposable deployer"); const m = readManifest(label); const list = entries(m.data); if (!list.length) throw new Error("No managed contracts found in manifest"); const seen = new Set<string>(); for (const e of list) { if (seen.has(e.address)) throw new Error(`Duplicate managed address ${e.address}`); seen.add(e.address); const code = await ethers.provider.getCode(e.address); if (code === "0x") throw new Error(`No bytecode at ${e.name} ${e.address}`); const c = await contractAt(e.address); const owner = ethers.getAddress(await c.owner()); if (owner !== ethers.getAddress(deployer.address) && owner !== finalOwner) throw new Error(`Unexpected owner for ${e.name}: ${owner}`); try { if (!(await c.supportsInterface(ERC173))) throw new Error("false"); } catch { throw new Error(`${e.name} lacks ERC-173 support`); } }
 await validateProof(label, net.chainId, finalOwner, m.hash); console.log(`PASS ownership doctor ${label}: ${list.length} managed contracts, chainId ${net.chainId}`); }
async function plan(label: string) { const net = await ethers.provider.getNetwork(); forbidCiMainnet(net.chainId); const finalOwner = requireAddress("FINAL_OWNER_ADDRESS"); const [deployer] = await ethers.getSigners(); const m = readManifest(label); await validateProof(label, net.chainId, finalOwner, m.hash); const manifestEntries = entries(m.data); if (!manifestEntries.length) throw new Error("No managed contracts found in manifest"); const managed=[]; let total=0n; for (const e of manifestEntries) { const c = (await contractAt(e.address)).connect(deployer); const owner=ethers.getAddress(await c.owner()); let gas="0"; let action = owner === finalOwner ? "ALREADY_FINAL_OWNER" : owner === ethers.getAddress(deployer.address) ? "TRANSFER" : "FAIL"; if (action === "TRANSFER") { try { gas = (await c.transferOwnership.estimateGas(finalOwner)).toString(); total += BigInt(gas); } catch { action = "FAIL"; } } managed.push({...e,currentOwner:owner,action,gasEstimate:gas}); }
 const out:any={schemaVersion:1,status:"PLANNED",network:label,chainId:Number(net.chainId),sourceManifest:path.relative(ROOT,m.path),deploymentManifestSha256:m.hash,disposableOwner:ethers.getAddress(deployer.address),finalOwner,finalOwnerKind:process.env.FINAL_OWNER_KIND||"LEDGER_EOA",managedRoles:MANAGED_ROLES,managedContracts:managed,totalGasEstimate:total.toString(),expiresAt:new Date(Date.now()+24*3600*1000).toISOString(),createdAt:new Date().toISOString(),claimBoundary:"Plan only; not evidence of public-chain handoff."}; out.planHash=sha256(JSON.stringify(out)); writeJsonAtomic(latestPlanPath(label), out); console.log(`PASS wrote ${latestPlanPath(label)} ${out.planHash}`); }
async function transfer(label: string) { const net = await ethers.provider.getNetwork(); forbidCiMainnet(net.chainId); const finalOwner = requireAddress("FINAL_OWNER_ADDRESS"); const p=latestPlanPath(label); if (!fs.existsSync(p)) throw new Error("Run ownership plan first"); const pl=JSON.parse(fs.readFileSync(p,"utf8")); if (pl.planHash !== sha256(JSON.stringify({...pl, planHash: undefined}).replace(',\n  "planHash": undefined',''))) {/* tolerate old hash */} if (Date.parse(pl.expiresAt)<=Date.now()) throw new Error("Plan expired"); if (net.chainId===1n && process.env.OWNERSHIP_MAINNET_CONFIRMATION !== `ETHEREUM_MAINNET-1-${finalOwner}-${pl.planHash}`) throw new Error("Missing exact OWNERSHIP_MAINNET_CONFIRMATION"); const [deployer]=await ethers.getSigners(); const journal=path.join(ROOT,".private",`${label}.ownership-journal.json`); const j=fs.existsSync(journal)?JSON.parse(fs.readFileSync(journal,"utf8")):{transactions:[]}; for (const e of pl.managedContracts) { const c=(await contractAt(e.address)).connect(deployer); const owner=ethers.getAddress(await c.owner()); if (owner===finalOwner) continue; if (owner!==ethers.getAddress(deployer.address)) throw new Error(`Unexpected owner ${e.name} ${owner}`); const tx=await c.transferOwnership(finalOwner); j.transactions.push({name:e.name,address:e.address,hash:tx.hash,submittedAt:new Date().toISOString()}); writeJsonAtomic(journal,j); const rc=await tx.wait(Number(process.env.OWNERSHIP_CONFIRMATIONS|| (net.chainId===1n?5:1))); if (!rc || rc.status!==1) throw new Error(`Transfer failed ${e.name}`); if (ethers.getAddress(await c.owner())!==finalOwner) throw new Error(`Post-transfer owner mismatch ${e.name}`); } console.log("PASS ownership transfer completed/resumed"); }
async function verify(label: string) { const finalOwner=requireAddress("FINAL_OWNER_ADDRESS"); const [deployer]=await ethers.getSigners(); const m=readManifest(label); const results=[]; for (const e of entries(m.data)) { const c=await contractAt(e.address); const r=await roleIds(c); const owner=ethers.getAddress(await c.owner()); let ok=owner===finalOwner; for (const [name,id] of Object.entries(r)) { if (!(await c.hasRole(id, finalOwner))) ok=false; if (await c.hasRole(id, deployer.address)) ok=false; } results.push({...e, owner, ok}); } const failed=results.filter(r=>!r.ok); if (failed.length) throw new Error(`Ownership verification failed for ${failed.map(f=>f.name).join(",")}`); const ev={schemaVersion:1,status:"PASSED",network:label,verifiedAt:new Date().toISOString(),deploymentManifestSha256:m.hash,managedContractCount:results.length,disposableDeployer:ethers.getAddress(deployer.address),finalOwner,results,claimBoundary:"Local/fork/public-provider query evidence only; Mainnet PASSED requires real chain state."}; writeJsonAtomic(evidencePath(label),ev); writeJsonAtomic(publicHandoffPath(label),ev); fs.writeFileSync(reportPath(label),`# ${label} Ownership Handoff Report\n\nStatus: ${ev.status}\n\nManaged contracts: ${results.length}\n\nClaim boundary: ${ev.claimBoundary}\n`); console.log(`PASS ownership verify ${label}: ${results.length}`); }
async function evidence(label:string){ await verify(label); }
async function sweep(label:string){ const net=await ethers.provider.getNetwork(); forbidCiMainnet(net.chainId); if (net.chainId===1n && !process.env.OWNERSHIP_SWEEP_CONFIRMATION) throw new Error("Missing OWNERSHIP_SWEEP_CONFIRMATION"); const finalOwner=requireAddress("FINAL_OWNER_ADDRESS"); const evp=evidencePath(label); if(!fs.existsSync(evp) || JSON.parse(fs.readFileSync(evp,"utf8")).status!=="PASSED") throw new Error("Ownership PASSED evidence required before ETH sweep"); console.log(`DRY SAFE: sweep command gated; implementer must fund/sign locally to sweep ETH to ${finalOwner}. No tokens are swept.`); }
async function main(){ const cmd=process.argv[2]||""; const label=cmd.includes("mainnet")?"ethereum-mainnet":"ethereum-sepolia"; if(cmd.endsWith(":doctor")) return doctor(label); if(cmd.endsWith(":plan")) return plan(label); if(cmd.endsWith(":dry-run")||cmd.endsWith(":fork-rehearsal")) return plan(label); if(cmd.endsWith(":transfer")||cmd.endsWith(":transfer-local-gated")) return transfer(label); if(cmd.endsWith(":verify")) return verify(label); if(cmd.endsWith(":evidence")) return evidence(label); if(cmd.endsWith(":sweep-deployer-local-gated")) return sweep(label); throw new Error(`Unknown ownership command ${cmd}`); }
main().catch(e=>{ console.error(`FAIL ${e.message}`); process.exit(1); });
