#!/usr/bin/env python3
"""Run Chromium interaction, adversarial, responsive, and visual QA for the Sovereign Machine Economy."""
from __future__ import annotations
import argparse,json,os,re,shutil
from pathlib import Path
from typing import Any

def write(path:Path,value:Any)->None:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def rec(items:list[dict[str,Any]],label:str,ok:bool,detail:Any='')->None:items.append({'label':label,'status':'PASS' if ok else 'FAIL','detail':detail})
def overflow(page:Any)->dict[str,Any]:return page.evaluate("""() => ({documentWidth:document.documentElement.scrollWidth,viewportWidth:document.documentElement.clientWidth,bodyWidth:document.body.scrollWidth,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+2})""")
def inline_page(site:Path,name:str,include_js:bool=True)->str:
 text=(site/name).read_text(encoding='utf-8');css=(site/'assets/sovereign-machine-economy.css').read_text(encoding='utf-8');js=(site/'assets/sovereign-machine-economy.js').read_text(encoding='utf-8').replace('</script','<\\/script')
 text=re.sub(r'<link\s+[^>]*rel=[\'\"]stylesheet[\'\"][^>]*>\s*','',text,flags=re.I);text=re.sub(r'<script\s+[^>]*src=[\'\"][^\'\"]+[\'\"][^>]*>\s*</script>\s*','',text,flags=re.I);text=text.replace('</head>',f'<style data-qa-inline>\n{css}\n</style>\n</head>',1)
 return text.replace('</body>',(f'<script>{js}</script>\n' if include_js else '')+'</body>',1)
def inline_homepage(site:Path)->str:
 text=(site/'index.html').read_text(encoding='utf-8')
 hrefs=re.findall(r'<link\s+[^>]*rel=[\'\"]stylesheet[\'\"][^>]*href=[\'\"]([^\'\"]+)',text,flags=re.I)
 parts=[]
 for href in hrefs:
  if href.startswith(('http://','https://','//')):continue
  path=site/href.split('?',1)[0]
  if path.is_file():parts.append(path.read_text(encoding='utf-8'))
 css='\n'.join(parts)
 text=re.sub(r'<link\s+[^>]*rel=[\'\"]stylesheet[\'\"][^>]*>\s*','',text,flags=re.I);text=re.sub(r'<script\s+[^>]*src=[\'\"][^\'\"]+[\'\"][^>]*>\s*</script>\s*','',text,flags=re.I)
 return text.replace('</head>',f'<style data-qa-inline-home>\n{css}\n</style>\n</head>',1)
def launch(playwright:Any)->Any:
 args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'];exe=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE') or os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('chromium-browser') or shutil.which('google-chrome')
 return playwright.chromium.launch(headless=True,executable_path=exe,args=args) if exe else playwright.chromium.launch(headless=True,args=args)
def wait_ready(page:Any)->None:page.wait_for_selector('html[data-sme-ready="true"]',timeout=15000)
def run_cycle(page:Any)->dict[str,Any]:
 page.locator('#sme-economy-form').evaluate('form => form.requestSubmit()');page.wait_for_function("window.__SME_STATE__ && window.__SME_STATE__.docket && !document.querySelector('#sme-run').disabled",timeout=25000);return page.evaluate('() => JSON.parse(JSON.stringify(window.__SME_STATE__))')
def shot(page:Any,selector:str,path:Path)->None:page.locator(selector).scroll_into_view_if_needed();page.wait_for_timeout(100);page.screenshot(path=str(path),full_page=False)
def run(site:Path,output:Path)->dict[str,Any]:
 try:from playwright.sync_api import sync_playwright
 except ImportError as exc:
  report={'schema':'goalos.sovereign_machine_economy.browser_qa.v1','status':'FAIL','checks_total':1,'checks_passed':0,'checks_failed':1,'checks':[{'label':'playwright-import','status':'FAIL','detail':str(exc)}]};write(output/'browser-report.json',report);return report
 output.mkdir(parents=True,exist_ok=True);checks=[];console=[];external=[];failed=[]
 experience=inline_page(site,'sovereign-machine-economy.html');architecture=inline_page(site,'sovereign-machine-economy-architecture.html');chronicle=inline_page(site,'sovereign-machine-economy-chronicle.html');atlas=inline_page(site,'sovereign-machine-economy-atlas.html');homepage=inline_homepage(site)
 with sync_playwright() as p:
  browser=launch(p)
  try:
   context=browser.new_context(viewport={'width':1600,'height':1000},device_scale_factor=1,reduced_motion='reduce',accept_downloads=True);page=context.new_page();page.set_default_timeout(15000)
   page.on('console',lambda m:console.append(f'{page.url}: {m.text}') if m.type=='error' else None);page.on('pageerror',lambda e:console.append(f'{page.url}: {e}'));page.on('request',lambda r:external.append(f'{r.method} {r.url}') if r.url.startswith(('http://','https://','ws://','wss://')) else None);page.on('requestfailed',lambda r:failed.append(f'{r.method} {r.url}: {r.failure}'))
   page.set_content(experience,wait_until='domcontentloaded');wait_ready(page)
   rec(checks,'experience-title',page.title()=='GoalOS Sovereign Machine Economy',page.title());rec(checks,'hero-visible',page.locator('#sme-hero-title').is_visible(),'');rec(checks,'six-hero-metrics',page.locator('#sme-hero-metrics > div').count()==6,page.locator('#sme-hero-metrics > div').count());rec(checks,'eighteen-gates',page.locator('.sme-gate').count()==18,page.locator('.sme-gate').count());rec(checks,'initial-meta-authorities',page.locator('#sme-meta-candidates > div').count()==9,page.locator('#sme-meta-candidates > div').count());rec(checks,'initial-node-peers',page.locator('#sme-peer-mesh > div').count()==12,page.locator('#sme-peer-mesh > div').count());rec(checks,'initial-jobs-guilds',page.locator('#sme-guild-grid > div').count()==12,page.locator('#sme-guild-grid > div').count());rec(checks,'desktop-no-overflow',not overflow(page)['overflow'],overflow(page));page.screenshot(path=str(output/'01-sovereign-machine-economy-hero-desktop.png'),full_page=False)
   state=run_cycle(page);rec(checks,'normal-terminal',state['terminal']=='HUMAN_SETTLEMENT_REVIEW',state['terminal']);rec(checks,'authority-none',state['docket']['authority']['external_authority']=='NONE_GRANTED',state['docket']['authority']);rec(checks,'thirty-six-artifacts',len(state['chain'])==36,len(state['chain']));rec(checks,'eighteen-complete-gates',page.locator('.sme-gate.is-complete').count()==18,page.locator('.sme-gate.is-complete').count());rec(checks,'selected-institution',page.locator('.sme-candidate.is-selected').count()==1,page.locator('.sme-candidate.is-selected').count());rec(checks,'primary-route-four',page.locator('.sme-peer.primary').count()==4,page.locator('.sme-peer.primary').count());rec(checks,'shadow-route-three',page.locator('.sme-peer.shadow').count()==3,page.locator('.sme-peer.shadow').count());rec(checks,'coalition-five',page.locator('.sme-guild.is-selected').count()==5,page.locator('.sme-guild.is-selected').count());rec(checks,'sealed-dots-36',page.locator('.sme-artifact-dot.is-sealed').count()==36,page.locator('.sme-artifact-dot.is-sealed').count());rec(checks,'three-handoff-hashes',all(len(state[x])==64 for x in ['institution_seal','node_seal','market_seal']),{x:state[x] for x in ['institution_seal','node_seal','market_seal']});rec(checks,'exports-enabled',not page.locator('#sme-download-json').is_disabled() and not page.locator('#sme-download-md').is_disabled(),'')
   shot(page,'#proof-flight',output/'02-eighteen-gate-proof-flight-desktop.png');shot(page,'#sme-meta-layer',output/'03-meta-agentic-institution-genesis-desktop.png');shot(page,'#sme-node-layer',output/'04-alpha-node-proof-execution-desktop.png');shot(page,'#sme-jobs-layer',output/'05-agi-jobs-accountable-value-desktop.png');shot(page,'#handoffs',output/'06-cryptographic-handoff-lattice-desktop.png');shot(page,'#chronicle-preview',output/'07-thirty-six-artifact-proof-chronicle-desktop.png')
   with page.expect_download() as info:page.locator('#sme-download-json').click()
   dl=info.value;dpath=output/'runtime-sovereign-economy-docket.json';dl.save_as(str(dpath));downloaded=json.loads(dpath.read_text(encoding='utf-8'));rec(checks,'json-download',downloaded.get('schema')=='goalos.sovereign_machine_economy.docket.v1' and downloaded.get('authority',{}).get('external_actions')==0,dl.suggested_filename)
   fingerprint={k:state[k] for k in ['institution_seal','node_seal','market_seal']};fingerprint['run']=state['docket']['run_commitment'];page.locator('#sme-reset').click();second=run_cycle(page);second_fp={k:second[k] for k in ['institution_seal','node_seal','market_seal']};second_fp['run']=second['docket']['run_commitment'];rec(checks,'deterministic-replay',fingerprint==second_fp,{'first':fingerprint,'second':second_fp})
   cases=[('institution-divergence','SAFE_HOLD',8),('node-identity-drift','SAFE_HOLD',20),('evidence-gap','DISPUTE_OPEN',35),('budget-breach','HUMAN_REVIEW_REQUIRED',36)]
   for incident,terminal,count in cases:
    page.locator('#sme-reset').click();page.locator(f'#sme-incident-{incident}').check();adverse=run_cycle(page);rec(checks,f'incident:{incident}:terminal',adverse['terminal']==terminal,adverse['terminal']);rec(checks,f'incident:{incident}:artifact-count',len(adverse['chain'])==count,len(adverse['chain']));rec(checks,f'incident:{incident}:authority',adverse['docket']['authority']['external_authority']=='NONE_GRANTED',adverse['docket']['authority'])
   page.locator('#sme-reset').click();page.locator('#sme-incident-node-identity-drift').check();run_cycle(page);shot(page,'#commission',output/'08-adversarial-safe-hold-desktop.png')
   page.set_content(architecture,wait_until='domcontentloaded');wait_ready(page);rec(checks,'architecture-title',page.title()=='Sovereign Machine Economy — Constitutional Architecture',page.title());rec(checks,'architecture-four-layers',page.locator('#sme-architecture-stack > article').count()==4,page.locator('#sme-architecture-stack > article').count());rec(checks,'architecture-six-handoff-rules',page.locator('#sme-handoff-protocol > article').count()==6,page.locator('#sme-handoff-protocol > article').count());rec(checks,'architecture-seven-guardians',page.locator('#sme-guardian-grid > article').count()==7,page.locator('#sme-guardian-grid > article').count());rec(checks,'architecture-three-lineages',page.locator('#sme-lineage-grid > article').count()==3,page.locator('#sme-lineage-grid > article').count());rec(checks,'architecture-no-overflow',not overflow(page)['overflow'],overflow(page));page.screenshot(path=str(output/'09-constitutional-architecture-desktop.png'),full_page=False);shot(page,'#separation',output/'10-separation-of-powers-desktop.png')
   page.set_content(chronicle,wait_until='domcontentloaded');wait_ready(page);rec(checks,'chronicle-title',page.title()=='Sovereign Machine Economy — Proof Chronicle',page.title());rec(checks,'chronicle-36-ledger-rows',page.locator('#sme-ledger > article').count()==36,page.locator('#sme-ledger > article').count());rec(checks,'chronicle-three-handoffs',page.locator('#sme-chronicle-handoffs > article').count()==3,page.locator('#sme-chronicle-handoffs > article').count());page.locator('#sme-ledger-search').fill('validator');rec(checks,'chronicle-search-filters',0<page.locator('#sme-ledger > article').count()<36,page.locator('#sme-ledger > article').count());page.locator('#sme-ledger-search').fill('');page.locator('button[data-layer="NODE"]').click();rec(checks,'chronicle-layer-filter',page.locator('#sme-ledger > article').count()==12,page.locator('#sme-ledger > article').count());rec(checks,'chronicle-no-overflow',not overflow(page)['overflow'],overflow(page));page.screenshot(path=str(output/'11-proof-chronicle-desktop.png'),full_page=False)
   page.set_content(atlas,wait_until='domcontentloaded');wait_ready(page);rec(checks,'atlas-title',page.title()=='Sovereign Machine Economy — Civilization Atlas',page.title());rec(checks,'atlas-three-columns',page.locator('#sme-atlas-map > section').count()==3,page.locator('#sme-atlas-map > section').count());rec(checks,'atlas-33-entities',page.locator('.sme-atlas-entity').count()==33,page.locator('.sme-atlas-entity').count());rec(checks,'atlas-eight-launches',page.locator('#sme-launch-grid > a').count()==8,page.locator('#sme-launch-grid > a').count());rec(checks,'atlas-no-overflow',not overflow(page)['overflow'],overflow(page));page.screenshot(path=str(output/'12-civilization-atlas-desktop.png'),full_page=False)
   page.set_content(homepage,wait_until='domcontentloaded');gateway=page.locator('.sme-home-gateway');gateway.scroll_into_view_if_needed();rec(checks,'homepage-gateway-once',gateway.count()==1 and gateway.is_visible(),gateway.count());rec(checks,'homepage-four-metrics',page.locator('.sme-home-metrics > div').count()==4,page.locator('.sme-home-metrics > div').count());rec(checks,'homepage-four-actions',page.locator('.sme-home-actions > a').count()==4,page.locator('.sme-home-actions > a').count());rec(checks,'homepage-three-stack-labels',page.locator('.sme-home-stack > span').count()==3,page.locator('.sme-home-stack > span').count());rec(checks,'homepage-no-overflow',not overflow(page)['overflow'],overflow(page));gateway.screenshot(path=str(output/'13-main-website-machine-economy-gateway-desktop.png'))
   page.set_viewport_size({'width':1024,'height':1366});page.set_content(experience,wait_until='domcontentloaded');wait_ready(page);rec(checks,'tablet-no-overflow',not overflow(page)['overflow'],overflow(page));page.screenshot(path=str(output/'14-machine-economy-tablet.png'),full_page=False)
   page.set_viewport_size({'width':390,'height':844});page.set_content(experience,wait_until='domcontentloaded');wait_ready(page);rec(checks,'mobile-no-overflow',not overflow(page)['overflow'],overflow(page));rec(checks,'mobile-form-visible',page.locator('#sme-economy-form').is_visible(),'');page.screenshot(path=str(output/'15-machine-economy-mobile.png'),full_page=False)
   page.set_content(homepage,wait_until='domcontentloaded');gateway=page.locator('.sme-home-gateway');gateway.scroll_into_view_if_needed();rec(checks,'homepage-mobile-no-overflow',not overflow(page)['overflow'],overflow(page));gateway.screenshot(path=str(output/'16-main-website-gateway-mobile.png'))
  finally:browser.close()
 rec(checks,'console-errors-zero',not console,console);rec(checks,'failed-requests-zero',not failed,failed);rec(checks,'external-requests-zero',not external,external)
 bad=[x for x in checks if x['status']=='FAIL'];report={'schema':'goalos.sovereign_machine_economy.browser_qa.v1','status':'PASS' if not bad else 'FAIL','checks_total':len(checks),'checks_passed':len(checks)-len(bad),'checks_failed':len(bad),'checks':checks,'console_errors':console,'failed_requests':failed,'external_requests':external};write(output/'browser-report.json',report);return report
def main()->int:
 root=Path(__file__).resolve().parents[2];ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--site',type=Path,default=root/'site');ap.add_argument('--output',type=Path,default=root/'site/qa/sovereign-machine-economy');a=ap.parse_args();report=run(a.site.resolve(),a.output.resolve());print(json.dumps({'status':report['status'],'checks_total':report['checks_total'],'checks_passed':report['checks_passed'],'checks_failed':report['checks_failed'],'output':str(a.output)},indent=2));return 0 if report['status']=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
