#!/usr/bin/env python3
from pathlib import Path
import shutil
SITE=Path('site')
TOKEN='0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA'
def write(path,text):
    p=SITE/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
def ensure_existing_site():
    if not SITE.exists() or not (SITE/'index.html').exists():
        raise SystemExit('Existing site missing. Build the existing website first; refusing destructive fallback.')
style='<style>.goalos-feature{margin:32px auto;padding:28px;border:1px solid #D8C48A;border-radius:24px;background:#fffaf0;max-width:1120px;box-shadow:0 18px 60px rgba(7,20,41,.10)}.goalos-feature h2{color:#071429;font-size:34px}.goalos-feature .buttons a{display:inline-block;margin:8px 8px 0 0;padding:11px 15px;border-radius:999px;background:#071429;color:#fff;text-decoration:none;font-weight:800}.goalos-feature .buttons a:nth-child(2){background:#B89445;color:#071429}.goalos-feature .tag{display:inline-block;background:#F8F1DF;border:1px solid #E3C673;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:900;color:#60480f;text-transform:uppercase}</style>'
page_css='body{margin:0;font-family:Inter,system-ui,sans-serif;background:#FBF7EF;color:#1C2430;line-height:1.58}header{background:#071429;padding:18px 32px;display:flex;justify-content:space-between}header a,header div{color:white;text-decoration:none;font-weight:800}.wrap{max-width:1160px;margin:0 auto;padding:48px 28px}.eyebrow{color:#B89445;font-weight:900;text-transform:uppercase;letter-spacing:.16em}h1{font-size:54px;color:#071429;line-height:.96}.lead{font-size:20px;color:#394252}.card{background:white;border:1px solid #e3d8bb;border-radius:22px;padding:24px;margin:18px 0}table{width:100%;border-collapse:collapse;background:white}th{background:#071429;color:white;text-align:left;padding:12px}td{border-top:1px solid #EFE5CB;padding:12px}.cta{background:#071429;color:white;border-radius:24px;padding:28px}.cta h2{color:#F8E6B0}footer{padding:36px;text-align:center;color:#657083}'
def base(title,body): return f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title><style>{page_css}</style></head><body><header><div>GoalOS AGIALPHA Ascension</div><a href="index.html">Home</a></header>{body}<footer>Illustrative until live Evidence Docket is completed.</footer></body></html>'
def main():
    ensure_existing_site(); (SITE/'assets').mkdir(exist_ok=True)
    for src in Path('docs/examples/assets').glob('*.png'): shutil.copy(src,SITE/'assets'/src.name)
    write('flagship-use-case.html',base('Flagship Use Case','<main class="wrap"><div class="eyebrow">Flagship use case</div><h1>Sovereign AI Procurement Control Tower</h1><p class="lead">GoalOS turns buyer trust into a proof mission. AGIALPHA coordinates the proof work. Reviewers validate evidence. Accepted artifacts earn scoped upgrade rights.</p><div class="cta"><h2>GoalOS turns buyer trust into proof.</h2><p>AGIALPHA coordinates mission posting, builder claim bonds, proof submission bonds, reviewer bonds, proof-card actions, credential actions and settlement.</p></div></main>'))
    write('proof-card-003.html',base('Proof Card 003',f'<main class="wrap"><div class="eyebrow">Proof Card 003</div><h1>Sovereign AI Procurement Control Tower</h1><p class="lead">Public-safe proof of a procurement trust workflow.</p><p>AGIALPHA token: {TOKEN}</p><p>RSI: proof-backed upgrade rights.</p></main>'))
    write('agialpha-ledger-route.html',base('AGIALPHA Smart Contract Route','<main class="wrap"><h1>Where AGIALPHA becomes useful</h1><p class="lead">GoalOSCommitRegistry, JobRegistry, JobClaimBondManager, ProofSubmissionRegistry, ReviewerBondRegistry, ProofCardRegistry, ProofCredentialRegistry, ReputationRegistry, AEPEvidenceDocketRegistry, AEPSelectionGate, AEPChronicleRegistry.</p></main>'))
    write('sovereign-rsi-control-plane.html',base('Sovereign RSI Control Plane','<main class="wrap"><h1>Recursive self-improvement through proof-backed upgrade rights</h1><p class="lead">The system improves efficiently by reusing only artifacts that survived evidence, evaluation, reviewer validation, scope control, challenge window, monitoring and rollback readiness.</p></main>'))
    write('trust-room-playbook.html',base('Trust Room Playbook','<main class="wrap"><h1>How to run the Trust Room mission</h1><ol><li>Collect buyer trust questions.</li><li>Create GoalOSCommit.</li><li>Post proof mission with AGIALPHA reward.</li><li>Builder creates trust-room workflow.</li><li>Reviewer validates evidence.</li><li>Publish Proof Card and Evidence Docket.</li></ol></main>'))
    write('share-flagship.html',base('Share Flagship Use Case','<main class="wrap"><h1>Share this proof narrative</h1><div class="cta"><h2>Public line</h2><p>GoalOS turns buyer trust into proof: AGIALPHA coordinates the mission, reviewers validate the evidence, Proof Cards create confidence, and only proven artifacts improve the next workflow.</p></div></main>'))
    for src,dst in [(Path('data/examples/proof-card-003-sovereign-ai-procurement-control-tower.json'),SITE/'data/examples/proof-card-003-sovereign-ai-procurement-control-tower.json'),(Path('evidence/examples/proof-card-003-evidence-docket-template.json'),SITE/'evidence/examples/proof-card-003-evidence-docket-template.json')]:
        if src.exists(): dst.parent.mkdir(parents=True,exist_ok=True); shutil.copy(src,dst)
    index=SITE/'index.html'; html=index.read_text(encoding='utf-8',errors='replace')
    feature=style+'<section class="goalos-feature" id="proof-card-003-feature"><span class="tag">Flagship use case</span><h2>Proof Card 003 - Sovereign AI Procurement Control Tower</h2><p>GoalOS turns buyer trust into proof: AGIALPHA coordinates the mission, reviewers validate the evidence, Proof Cards create confidence, and only proven artifacts improve the next workflow.</p><div class="buttons"><a href="flagship-use-case.html">Open flagship use case</a><a href="agialpha-ledger-route.html">See AGIALPHA route</a><a href="sovereign-rsi-control-plane.html">See sovereign RSI</a></div></section>'
    if 'proof-card-003-feature' not in html: html=html.replace('</body>',feature+'</body>') if '</body>' in html else html+feature
    index.write_text(html,encoding='utf-8')
    print('Flagship Proof Card 003 added.')
if __name__=='__main__': main()
