#!/usr/bin/env python3
from pathlib import Path
import argparse, re, json, html
NAVY='#071426'; GOLD='#B78B32'; IVORY='#F7F2EA'; INK='#17233A'; MUTED='#64748B'
proof_cards=[
('001','Buyer Rescue Workflow','Turns a buyer support problem into a reviewed workflow improvement.'),
('002','Sovereign Procurement Trust Room','Converts procurement trust into a proof mission and Evidence Docket.'),
('003','Sovereign AI Procurement Control Tower','Builds a control tower for trust, governance, rollout, and rollback.'),
('004','Persistent Goal-Seeking Intelligence Accumulation Engine','Shows capability, evidence, and economic value accumulating over time.'),
('005','Sovereign RSI Value-to-Capability Treasury','Routes verified value into stronger future capability.'),
('006','Sovereign Enterprise RSI Operating System','Coordinates a large specialist-agent enterprise through proof.'),
('007','Sovereign Enterprise Autoresearch Reactor','Runs parallel proof missions, evaluator harnesses, and selection.'),
('008','Sovereign Corporate Capability Foundry','Allocates proof mission portfolios across high-value corporate domains.'),
('009','Cyber-Sovereign Execution Moat','Turns defensive cyber work into proof-backed capability.'),
('010','Cyber-Sovereign Proof Benchmark Market','Turns defensive cyber work into replayable benchmark wins and external evidence.')]
STATEMENT='GoalOS-native alpha-AGI Ascension turns cyber-sovereign defensive work into replayable proof benchmarks: AGIALPHA coordinates missions, specialist agents execute, reviewers and red teams validate, independent reproduction hardens the result, and only proven artifacts earn scoped upgrade rights.'
CSS='''
:root{--navy:#071426;--gold:#B78B32;--ivory:#F7F2EA;--ink:#17233A;--muted:#64748B}.pc-section{background:#F7F2EA;color:#17233A;padding:72px 28px;border-top:1px solid #e5dece;border-bottom:1px solid #e5dece}.pc-wrap{max-width:1180px;margin:0 auto}.pc-kicker{color:#B78B32;font-weight:900;letter-spacing:.16em;text-transform:uppercase;font-size:12px}.pc-title{font-size:clamp(34px,5vw,64px);line-height:1;margin:16px 0;color:#071426;letter-spacing:-.045em}.pc-lede{font-size:20px;color:#334155;max-width:920px}.pc-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px;margin-top:28px}.pc-card{grid-column:span 4;background:white;border:1px solid #e5dece;border-radius:24px;padding:24px;text-decoration:none;box-shadow:0 12px 34px rgba(7,20,38,.07);color:#17233A}.pc-card .num{font-weight:900;color:#B78B32;letter-spacing:.12em;font-size:12px;text-transform:uppercase}.pc-card h3{font-size:20px;line-height:1.1;margin:10px 0;color:#071426}.pc-card p{font-size:15px;color:#526174}.pc-button{display:inline-block;background:#071426;color:white!important;padding:12px 18px;border-radius:999px;font-weight:900;text-decoration:none;margin-top:20px}.pc-page{background:#F7F2EA;color:#17233A;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;line-height:1.55}.pc-topbar{background:#071426;color:white;padding:18px 30px;display:flex;justify-content:space-between;position:sticky;top:0;z-index:10}.pc-topbar a{color:white;text-decoration:none;margin-left:18px;font-weight:800}.pc-hero{max-width:1180px;margin:0 auto;padding:72px 28px 44px}.pc-hero h1{font-size:clamp(42px,6vw,78px);line-height:.98;margin:18px 0;color:#071426;letter-spacing:-.055em}.pc-section2{max-width:1180px;margin:0 auto;padding:45px 28px}.pc-panel{background:white;border:1px solid #e5dece;box-shadow:0 18px 50px rgba(7,20,38,.08);border-radius:28px;padding:30px;margin:22px 0}.pc-panel-dark{background:#071426;color:white;border-radius:28px;padding:30px;margin:22px 0}.pc-panel-dark p{color:#dbe4f0}.pc-flow{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-top:20px}.pc-step{background:white;border:1px solid #e5dece;border-radius:18px;padding:18px;text-align:center;font-weight:800}.pc-table{width:100%;border-collapse:separate;border-spacing:0;border:1px solid #e5dece;border-radius:18px;overflow:hidden;background:white;margin:22px 0}.pc-table th{background:#071426;color:white;text-align:left;padding:13px;font-size:13px}.pc-table td{padding:13px;border-top:1px solid #e5dece;vertical-align:top;font-size:14px}.pc-badge{display:inline-block;background:#f4ead6;color:#7c5b15;border:1px solid #e3c986;border-radius:999px;padding:6px 12px;font-size:12px;font-weight:900;text-transform:uppercase;margin:4px}.pc-footer{max-width:1180px;margin:0 auto;padding:60px 28px;color:#64748b;border-top:1px solid #e5dece}@media(max-width:900px){.pc-card{grid-column:span 12}.pc-flow{grid-template-columns:1fr}}
'''
def cards_grid():
    return '<div class="pc-grid">'+''.join([f'<a class="pc-card" href="proof-card-{n}.html"><div class="num">Proof Card {n}</div><h3>{html.escape(t)}</h3><p>{html.escape(d)}</p></a>' for n,t,d in proof_cards])+'</div>'
def full_page(title, body):
    return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><style>{CSS}</style></head><body class="pc-page"><div class="pc-topbar"><strong>GoalOS AGIALPHA Ascension</strong><span><a href="index.html">Home</a><a href="proof-cards.html">Proof Cards</a><a href="agialpha-ledger-route.html">AGIALPHA</a><a href="sovereign-rsi-control-plane.html">RSI</a></span></div>{body}<div class="pc-footer"><strong>Claim boundary:</strong> illustrative until live Evidence Dockets are completed. No claim of achieved AGI, superintelligence, guaranteed financial return, legal/tax/security approval, Ethereum mainnet deployment, offensive cyber capability, or Kardashev Type II achievement.</div></body></html>'
def pc010_body():
    return f'''<div class="pc-hero"><div class="pc-kicker">Proof Card 010 / Execution Moat</div><h1>Cyber-Sovereign Proof Benchmark Market</h1><p class="pc-lede">{STATEMENT}</p><span class="pc-badge">Replayable Evidence</span><span class="pc-badge">Cyber-Sovereign</span><span class="pc-badge">AGIALPHA Settlement</span><span class="pc-badge">RSI Upgrade Rights</span></div><section class="pc-section2"><div class="pc-panel-dark"><h2>Execution moat upgrade</h2><p>Proof Card 010 turns defensive cyber work into a replayable benchmark market: task manifest, baseline, evaluator harness, ProofBundle, reviewer attestation, red-team report, reproduction receipt, SelectionCertificate, rollback path, AGIALPHA settlement, and Chronicle memory.</p></div></section><section class="pc-section2"><h2>Execution moat ladder</h2><div class="pc-flow"><div class="pc-step">Architecture</div><div class="pc-step">Evidence</div><div class="pc-step">Replay</div><div class="pc-step">Review</div><div class="pc-step">Adoption</div></div></section><section class="pc-section2"><h2>Where AGIALPHA becomes useful</h2><table class="pc-table"><tr><th>Use</th><th>Purpose</th></tr><tr><td>Mission budgets</td><td>Sponsors fund authorized proof missions.</td></tr><tr><td>Builder / proof / reviewer bonds</td><td>Execution, submission, and validation become accountable.</td></tr><tr><td>Reward vault settlement</td><td>Accepted work settles through a transparent proof route.</td></tr><tr><td>Credentials and reputation</td><td>Accepted work improves future routing.</td></tr><tr><td>Reinvestment</td><td>Verified value funds stronger agents, harnesses, audits, and missions.</td></tr></table></section><section class="pc-section2"><h2>Registry route</h2><p>AEPGoalOSCommitRegistry -> AEPRunCommitmentRegistry -> CyberBenchmarkRegistry -> JobRegistry -> JobClaimBondManager -> ProofSubmissionRegistry -> ReviewerBondRegistry -> RedTeamChallengeRegistry -> ProofCardRegistry -> ProofCredentialRegistry -> ReputationRegistry -> AEPEvidenceDocketRegistry -> AEPSelectionGate -> AEPRollbackRegistry -> AEPChronicleRegistry -> AlphaWorkUnitLedger -> AEPRewardVault -> TreasuryRouter.</p></section><section class="pc-section2"><h2>Recursive Self-Improvement mechanism</h2><p>Only reproduced, reviewed, bounded, and rollback-ready artifacts can influence the next mission.</p></section>'''
def write_pages(site):
    site=Path(site); site.mkdir(parents=True, exist_ok=True)
    # Update homepage additively
    idx=site/'index.html'
    section=f'''<!-- GOALOS_PROOF_CARDS_V16_START --><section class="pc-section"><div class="pc-wrap"><div class="pc-kicker">Proof Card Command Center</div><h2 class="pc-title">Proof Cards 001-010</h2><p class="pc-lede">GoalOS turns AI work into proof. AGIALPHA coordinates proof-settled missions. Evidence Dockets make claims auditable. RSI reuses only what proved itself.</p>{cards_grid()}<a class="pc-button" href="proof-cards.html">Open all Proof Cards</a></div></section><!-- GOALOS_PROOF_CARDS_V16_END -->'''
    if idx.exists():
        htmltxt=idx.read_text(encoding='utf-8', errors='replace')
        if '</head>' in htmltxt and 'GOALOS_PROOF_CARDS_V16_CSS' not in htmltxt:
            htmltxt=htmltxt.replace('</head>', f'<style id="GOALOS_PROOF_CARDS_V16_CSS">{CSS}</style></head>')
        htmltxt=re.sub(r'<!-- GOALOS_PROOF_CARDS_V16_START -->.*?<!-- GOALOS_PROOF_CARDS_V16_END -->', section, htmltxt, flags=re.S)
        if 'GOALOS_PROOF_CARDS_V16_START' not in htmltxt:
            htmltxt=htmltxt.replace('</body>', section+'</body>') if '</body>' in htmltxt else htmltxt+section
        idx.write_text(htmltxt, encoding='utf-8')
    else:
        idx.write_text(full_page('GoalOS AGIALPHA Ascension', f'<div class="pc-hero"><div class="pc-kicker">GoalOS AGIALPHA Ascension</div><h1>Proof-backed sovereign intelligence.</h1><p class="pc-lede">GoalOS turns AI work into proof. AGIALPHA coordinates proof-settled missions. Evidence Dockets make claims auditable. RSI reuses only what proved itself.</p></div>{section}'), encoding='utf-8')
    site.joinpath('proof-cards.html').write_text(full_page('Proof Cards', f'<div class="pc-hero"><div class="pc-kicker">Proof Card Portfolio</div><h1>Proof Cards 001-010</h1><p class="pc-lede">Every proof card has a stable page, proof mission, AGIALPHA route, Evidence Docket checklist, RSI upgrade logic, and claim boundary.</p></div><section class="pc-section2">{cards_grid()}</section>'), encoding='utf-8')
    for n,t,d in proof_cards[:-1]:
        site.joinpath(f'proof-card-{n}.html').write_text(full_page(f'Proof Card {n} - {t}', f'<div class="pc-hero"><div class="pc-kicker">Proof Card {n}</div><h1>{html.escape(t)}</h1><p class="pc-lede">{html.escape(d)}</p></div><section class="pc-section2"><div class="pc-panel"><h2>Stable proof-card page</h2><p>This page is preserved and connected to the main proof-card gallery.</p></div></section>'), encoding='utf-8')
    site.joinpath('proof-card-010.html').write_text(full_page('Proof Card 010 - Cyber-Sovereign Proof Benchmark Market', pc010_body()), encoding='utf-8')
    site.joinpath('agialpha-ledger-route.html').write_text(full_page('AGIALPHA Ledger Route','<div class="pc-hero"><div class="pc-kicker">AGIALPHA Route</div><h1>Where AGIALPHA becomes useful</h1><p class="pc-lede">AGIALPHA coordinates mission budgets, bonds, proof submission, review, red-team challenge, proof-card actions, credentials, reputation, settlement, and reinvestment.</p></div>'), encoding='utf-8')
    site.joinpath('sovereign-rsi-control-plane.html').write_text(full_page('Sovereign RSI','<div class="pc-hero"><div class="pc-kicker">Sovereign RSI</div><h1>Recursive Self-Improvement through proof-backed upgrade rights</h1><p class="pc-lede">The system improves efficiently because unproven artifacts cannot become future operating context.</p></div>'), encoding='utf-8')
    site.joinpath('evidence-docket.html').write_text(full_page('Evidence Docket','<div class="pc-hero"><div class="pc-kicker">Evidence Docket</div><h1>Evidence makes claims auditable</h1><p class="pc-lede">Every serious proof needs a task manifest, baseline, ProofBundle, reviewer attestation, red-team report, reproduction receipt, SelectionCertificate, rollback path, and Chronicle entry.</p></div>'), encoding='utf-8')
    site.joinpath('season-001.html').write_text(full_page('Season 001','<div class="pc-hero"><div class="pc-kicker">Season 001</div><h1>From proof cards to live evidence</h1><p class="pc-lede">The next milestone is to convert the proof cards into live Evidence Dockets with replayable, externally checkable results.</p></div>'), encoding='utf-8')
    site.joinpath('share.html').write_text(full_page('Share','<div class="pc-hero"><div class="pc-kicker">Share</div><h1>Public line</h1><p class="pc-lede">GoalOS turns cyber-sovereign work into replayable proof. AGIALPHA coordinates the mission. Reviewers validate the evidence. Only reproduced proof earns upgrade rights.</p></div>'), encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--site', default='site'); args=ap.parse_args(); write_pages(args.site); print('Main website augmented with Proof Cards 001-010.')
if __name__=='__main__': main()
