#!/usr/bin/env python3
from pathlib import Path
import json, argparse, html, shutil, subprocess, sys

NAVY='#06142c'; INK='#17233d'; GOLD='#b9964a'; IVORY='#fbf8f0'; CARD='#ffffff'; PALE='#f3efe4'; GREEN='#1f7a4d'

proof_cards = [
 {"id":"001","title":"Buyer Rescue Workflow","subtitle":"Support workflow improvement for buyers who cannot access a file.","url":"proof-card-001.html","focus":"Simple buyer trust","agialpha":"optional / illustrative coordination until live evidence","rsi":"turns a solved support weakness into a reusable support artifact"},
 {"id":"002","title":"Sovereign Procurement Trust Room","subtitle":"A procurement-ready trust room for buyer due diligence.","url":"proof-card-002.html","focus":"Enterprise trust","agialpha":"coordinates proof mission, builder, reviewer, credential, reputation","rsi":"turns validated due-diligence answers into reusable trust artifacts"},
 {"id":"003","title":"Sovereign AI Procurement Control Tower","subtitle":"Control-plane proof for AI adoption, governance, review, rollback, and auditability.","url":"proof-card-003.html","focus":"Institutional control","agialpha":"coordinates proof-settled governance work and evidence routing","rsi":"accepted procurement control artifacts improve future procurement workflows"},
 {"id":"004","title":"Persistent Goal-Seeking Intelligence Accumulation Engine","subtitle":"Experimental framework for persistent goals, evidence memory, capability accumulation, and economic value tracking.","url":"proof-card-004.html","focus":"System compounding","agialpha":"coordinates proof work, credentials, reputation, settlement, and access across repeated missions","rsi":"proof-backed upgrade rights let only validated artifacts shape future work"},
]

contract_route = ["AEPGoalOSCommitRegistry", "AEPRunCommitmentRegistry", "JobRegistry", "JobClaimBondManager", "ProofSubmissionRegistry", "ReviewerBondRegistry", "ProofCardRegistry", "ProofCredentialRegistry", "ReputationRegistry", "AEPEvidenceDocketRegistry", "AEPSelectionGate", "AEPChronicleRegistry"]

def write(p, s):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding='utf-8')

def page(title, body):
    nav = '<a href="index.html">Home</a><a href="proof-cards.html">Proof Cards</a><a href="agialpha-ledger-route.html">AGIALPHA Route</a><a href="sovereign-rsi-control-plane.html">Sovereign RSI</a><a href="evidence-docket.html">Evidence Docket</a><a href="season-001.html">Season 001</a>'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><style>
:root{{--navy:{NAVY};--ink:{INK};--gold:{GOLD};--ivory:{IVORY};--pale:{PALE};--green:{GREEN}}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--ivory);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial,sans-serif;line-height:1.55}} a{{color:inherit}} .top{{background:var(--navy);color:#fff;padding:18px 34px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:2;box-shadow:0 8px 28px rgba(6,20,44,.16)}} .brand{{font-weight:900;letter-spacing:-.02em}} .top nav{{display:flex;gap:18px;flex-wrap:wrap}} .top nav a{{font-weight:800;text-decoration:none;font-size:13px;opacity:.9}} .wrap{{max-width:1160px;margin:0 auto;padding:64px 30px}} .eyebrow{{font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:var(--gold);font-weight:950}} h1{{font-size:clamp(38px,6vw,72px);line-height:.96;letter-spacing:-.06em;margin:14px 0 20px;color:var(--navy)}} h2{{font-size:clamp(26px,3.2vw,42px);line-height:1.05;letter-spacing:-.045em;color:var(--navy);margin:46px 0 16px}} h3{{font-size:22px;line-height:1.15;letter-spacing:-.025em;color:var(--navy)}} .lead{{font-size:19px;max-width:900px;color:#34425c}} .grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px;margin:28px 0}} .card{{background:#fff;border:1px solid #e6decf;border-radius:24px;padding:24px;box-shadow:0 18px 44px rgba(6,20,44,.08)}} .hero{{background:linear-gradient(135deg,#06142c,#102852);color:white;border-radius:34px;padding:42px;margin:34px 0;box-shadow:0 25px 70px rgba(6,20,44,.22)}} .hero h2,.hero h3{{color:white;margin-top:0}} .hero .lead{{color:#e7eefc}} .pill{{display:inline-flex;background:#efe3bd;color:#2d250e;border-radius:999px;padding:8px 12px;font-weight:900;font-size:12px;letter-spacing:.05em;text-transform:uppercase;margin:3px}} .step{{display:flex;gap:15px;align-items:flex-start;border-left:4px solid var(--gold);padding:12px 0 12px 18px;margin:8px 0}} .num{{background:var(--navy);color:#fff;border-radius:50%;min-width:34px;height:34px;display:grid;place-items:center;font-weight:900}} table{{width:100%;border-collapse:collapse;background:white;border-radius:18px;overflow:hidden;margin:18px 0;box-shadow:0 12px 28px rgba(6,20,44,.06)}} th{{background:var(--navy);color:white;text-align:left;padding:14px;font-size:13px}} td{{border-top:1px solid #ede5d8;padding:14px;vertical-align:top;font-size:14px}} .quote{{font-size:26px;line-height:1.18;color:var(--navy);font-weight:900;border-left:6px solid var(--gold);padding:10px 0 10px 22px;margin:26px 0}} .safe{{background:#f8f4e9;border:1px solid #e6decf;border-radius:20px;padding:20px;margin-top:30px}} .footer{{padding:30px;text-align:center;color:#667089;font-size:13px}} code{{background:#f1eee8;border-radius:8px;padding:2px 5px}} @media(max-width:800px){{.top{{align-items:flex-start;gap:12px;flex-direction:column}}}}
</style></head><body><header class="top"><div class="brand">GoalOS AGIALPHA Ascension</div><nav>{nav}</nav></header><main class="wrap">{body}</main><footer class="footer">Illustrative until live Evidence Docket is completed. The intelligence stays private. The proof becomes verifiable.</footer></body></html>'''

def card_tile(c):
    return f'''<article class="card"><div class="eyebrow">Proof Card {c['id']}</div><h3>{html.escape(c['title'])}</h3><p>{html.escape(c['subtitle'])}</p><p><b>Focus:</b> {html.escape(c['focus'])}</p><p><b>RSI:</b> {html.escape(c['rsi'])}</p><a class="pill" href="{c['url']}">Open card</a></article>'''

def proof_card_page(c):
    is4 = c['id']=='004'
    if is4:
        sections = '''<section class="hero"><div class="eyebrow">Proof statement</div><h2>Persistent, goal-seeking, self-improving intelligence framework.</h2><p class="lead">GoalOS AGIALPHA Ascension is an experimental framework for a persistent, goal-seeking, self-improving intelligence system that accumulates capabilities, evidence, and economic value over time.</p></section>
<div class="grid"><div class="card"><h3>Capabilities</h3><p>Validated workflows, rubrics, policies, procurement responses, support playbooks, rollback plans, and mission templates become reusable capability.</p></div><div class="card"><h3>Evidence</h3><p>ProofBundles, reviewer attestations, Evidence Dockets, challenge outcomes, replay logs, Selection Certificates, and Chronicle entries accumulate as institutional memory.</p></div><div class="card"><h3>Economic value</h3><p>Value means measured productivity, lower repeated work, sponsor demand, buyer trust, better routing, and proof-backed capability. It does not mean token price or investment return.</p></div></div>
<h2>How RSI becomes efficient</h2><p>RSI is implemented as proof-backed upgrade rights. An artifact cannot shape future work merely because it exists. It must survive evidence, evaluation, reviewer validation, scope control, challenge window, monitoring, rollback readiness, and Selection Gate approval.</p>
<div class="grid"><div class="card"><h3>Observe</h3><p>Find a weakness in a prior workflow, trust response, evidence template, or review path.</p></div><div class="card"><h3>Improve</h3><p>Generate a candidate artifact under a bounded GoalOS mission.</p></div><div class="card"><h3>Prove</h3><p>Submit proof, cost/risk notes, reviewer package, and public-safe Proof Card.</p></div><div class="card"><h3>Select</h3><p>Selection Gate grants scoped upgrade rights only if evidence and rollback obligations pass.</p></div></div>'''
    else:
        sections = f'''<section class="hero"><h2>{html.escape(c['subtitle'])}</h2><p class="lead">This proof card demonstrates how GoalOS turns a specific adoption friction into proof, and how AGIALPHA coordinates the proof-work route.</p></section>
<div class="grid"><div class="card"><h3>Problem</h3><p>A buyer, sponsor, or reviewer needs more than an AI answer; they need an auditable reason to trust the workflow.</p></div><div class="card"><h3>Mission</h3><p>GoalOS defines a proof mission. A builder creates an improved artifact. Reviewers validate evidence.</p></div><div class="card"><h3>Result</h3><p>A Proof Card, credential, reputation update, and Evidence Docket make the improvement reusable.</p></div></div>'''
    route = ''.join(f'<div class="step"><div class="num">{i+1}</div><div><b>{html.escape(x)}</b><br><span>Public-safe state transition for proof-settled work.</span></div></div>' for i,x in enumerate(contract_route))
    body = f'''<div class="eyebrow">Proof Card {c['id']}</div><h1>{html.escape(c['title'])}</h1><p class="lead">{html.escape(c['subtitle'])}</p>{sections}<h2>Where AGIALPHA becomes useful</h2><div class="grid"><div class="card"><h3>Coordination</h3><p>{html.escape(c['agialpha'])}</p></div><div class="card"><h3>Bonds and review</h3><p>Mission posting, builder claim bond, proof submission bond, reviewer bond, proof-card action, credential action, reward settlement, and reputation-linked access.</p></div><div class="card"><h3>Claim boundary</h3><p>Experimental proof artifact until live Evidence Docket is complete. No achieved AGI, guaranteed ROI, legal/tax/security approval, or mainnet deployment claim.</p></div></div><h2>Smart-contract / registry route</h2>{route}<h2>Evidence Docket checklist</h2><table><tr><th>Evidence class</th><th>What should be captured</th></tr><tr><td>Commitment</td><td>GoalOSCommit, mission scope, success metric, authority, risk class, rollback expectation.</td></tr><tr><td>Execution</td><td>RunCommitment, workflow artifact, output hash, context root, tool list, cost/risk notes.</td></tr><tr><td>Validation</td><td>Reviewer attestation, challenge window, rejection criteria, accepted proof-card hash.</td></tr><tr><td>Evolution</td><td>SelectionCertificate, scoped upgrade rights, Chronicle entry, rollback path.</td></tr></table>'''
    return page('Proof Card '+c['id'], body)

def build_site(out):
    out.mkdir(parents=True, exist_ok=True)
    # Homepage
    cards_html = ''.join(card_tile(c) for c in proof_cards)
    body = f'''<div class="eyebrow">GoalOS AGIALPHA Ascension</div><h1>Four Proof Cards for proof-governed intelligence.</h1><p class="lead">GoalOS turns AI adoption into proof. AGIALPHA coordinates proof-settled work. Evidence Dockets make claims auditable. Sovereign RSI reuses only what proved itself.</p><section class="hero"><div class="eyebrow">Flagship proof system</div><h2>From individual proof cards to persistent intelligence accumulation.</h2><p class="lead">Proof Card 004 explains the compounding layer: a persistent, goal-seeking, self-improving framework that accumulates capabilities, evidence, and economic value over time - with strict claim boundaries.</p><a class="pill" href="proof-card-004.html">Open Proof Card 004</a><a class="pill" href="proof-cards.html">View all four cards</a></section><h2>Visible proof cards</h2><div class="grid">{cards_html}</div>'''
    write(out/'index.html', page('GoalOS AGIALPHA Ascension', body))
    write(out/'proof-cards.html', page('Proof Cards', f'<div class="eyebrow">Proof Gallery</div><h1>All four proof cards.</h1><p class="lead">Each card explains a public-safe proof route, AGIALPHA coordination layer, Evidence Docket, and RSI upgrade logic.</p><div class="grid">{cards_html}</div>'))
    for c in proof_cards:
        write(out/c['url'], proof_card_page(c))
    route_table = '<table><tr><th>Step</th><th>Registry / contract</th><th>Purpose</th></tr>' + ''.join(f'<tr><td>{i+1}</td><td>{html.escape(x)}</td><td>Coordinates proof, review, credential, reputation, evidence, selection, or chronicle state.</td></tr>' for i,x in enumerate(contract_route)) + '</table>'
    write(out/'agialpha-ledger-route.html', page('AGIALPHA Ledger Route', f'<div class="eyebrow">AGIALPHA Utility Route</div><h1>Where AGIALPHA becomes useful.</h1><p class="lead">AGIALPHA coordinates proof work when sponsors, builders, and reviewers need shared proof, bonds, settlement, credentials, reputation, and access logic.</p>{route_table}<section class="safe"><b>Boundary:</b> AGIALPHA is shown as a utility coordination asset for proof-settled work, not as an investment promise, yield product, revenue share, or guaranteed value instrument.</section>'))
    rsi_body = '''<div class="eyebrow">Sovereign RSI</div><h1>Recursive self-improvement through proof-backed upgrade rights.</h1><p class="lead">The system improves efficiently by reusing only artifacts that survived evidence, evaluation, reviewer validation, scope control, challenge window, monitoring, and rollback readiness.</p><div class="grid"><div class="card"><h3>1. Detect weakness</h3><p>Prior proof cards, buyer friction, or procurement reviews reveal a weakness.</p></div><div class="card"><h3>2. Produce candidate</h3><p>A builder creates an improved workflow, rubric, evidence template, or trust artifact.</p></div><div class="card"><h3>3. Prove and review</h3><p>Evidence, reviewer attestation, Proof Card, and Evidence Docket are produced.</p></div><div class="card"><h3>4. Gate and propagate</h3><p>Selection Gate grants scoped upgrade rights. Unproven artifacts do not propagate.</p></div></div><p class="quote">RSI becomes useful when improvement earns the right to shape future work.</p>'''
    write(out/'sovereign-rsi-control-plane.html', page('Sovereign RSI Control Plane', rsi_body))
    ev_body = '''<div class="eyebrow">Evidence Docket</div><h1>The proof room for claims.</h1><p class="lead">The Evidence Docket collects the public-safe evidence needed to understand what was claimed, what was done, who reviewed it, what passed, what failed, what can be reused, and what must remain private.</p><table><tr><th>Docket section</th><th>Required content</th></tr><tr><td>Claim</td><td>Public-safe statement and explicit boundary.</td></tr><tr><td>Commitment</td><td>GoalOSCommit, mission scope, success metric, risk class.</td></tr><tr><td>Proof</td><td>ProofBundle, output hashes, scorecard, review package.</td></tr><tr><td>Review</td><td>Reviewer attestation, challenge window, acceptance or rejection.</td></tr><tr><td>Evolution</td><td>SelectionCertificate, scoped upgrade rights, Chronicle entry, rollback path.</td></tr></table>'''
    write(out/'evidence-docket.html', page('Evidence Docket', ev_body))
    season = ''.join(card_tile(c) for c in proof_cards)
    write(out/'season-001.html', page('Season 001', f'<div class="eyebrow">Season 001</div><h1>Proof missions that create demand.</h1><p class="lead">Season 001 should start with proof cards that are understandable, useful, and progressively more institutional.</p><div class="grid">{season}</div>'))
    write(out/'persistent-intelligence-accumulation.html', proof_card_page(proof_cards[-1]))
    write(out/'share.html', page('Share', '<div class="eyebrow">Share Kit</div><h1>Public copy.</h1><p class="quote">GoalOS turns AI adoption into proof. AGIALPHA coordinates proof work. Evidence Dockets make claims auditable. Sovereign RSI reuses only what proved itself.</p><p>Proof Card 004 shows the compounding layer: persistent goals, evidence memory, capability accumulation, and economic value tracking over time.</p>'))
    data_dir = out/'data'; data_dir.mkdir(exist_ok=True)
    write(data_dir/'proof-card-004.json', json.dumps({"proof_card_004": proof_cards[-1], "route": contract_route}, indent=2))
    write(out/'sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + ''.join(f'<url><loc>{{BASE}}/{p.name}</loc></url>' for p in out.glob('*.html')) + '</urlset>')


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--out', default='site')
    args=ap.parse_args()
    out=Path(args.out)
    if out.exists():
        # Preserve unknown files by not deleting, but overwrite known generated pages.
        pass
    else:
        out.mkdir(parents=True)
    build_site(out)
    print(f'Built four proof card site at {out}')

if __name__=='__main__': main()
