#!/usr/bin/env python3
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
state = json.loads((ROOT / "qa/mainnet-release-state.json").read_text())
manifest = json.loads((ROOT / "deployments/ethereum-mainnet.agialpha.latest.json").read_text())
verification_path = ROOT / "qa/mainnet-postdeploy/verification-evidence.json"
runtime_path = ROOT / "qa/mainnet-postdeploy/runtime-bytecode-report.json"
verification = json.loads(verification_path.read_text()) if verification_path.exists() else {"contracts": []}
runtime_report = json.loads(runtime_path.read_text()) if runtime_path.exists() else {}
verification_by_name = {item.get("name"): item for item in verification.get("contracts", [])}
verification_by_address = {str(item.get("address", "")).lower(): item for item in verification.get("contracts", [])}
contracts = manifest["contracts"]
TAG = "v4.4.0-mainnet-2026-06-21"
SHA = "51bacf4fe58e4eb425240e74eef7e8461832767f"

def evidence_for(c):
    return verification_by_name.get(c["name"]) or verification_by_address.get(c["address"].lower()) or {}

def verification_status(c, ev, external):
    if external:
        return ev.get("etherscanStatus") or "skipped_external"
    status = ev.get("etherscanStatus") or c.get("verified") or "UNKNOWN"
    if ev.get("verified") is True and status == "verified":
        return "verified"
    return status

def entry(c):
    external = c.get("classification") == "external" or c["name"] == "AGIALPHA"
    ev = evidence_for(c)
    return {
        "name": c["name"],
        "address": c["address"],
        "chainId": c.get("chainId", 1),
        "external": external,
        "deployedByGoalOS": not external,
        "mintedByGoalOS": False if external else None,
        "category": "external-token" if external else "goalos-contract",
        "fullyQualifiedContractName": None if external else c.get("fullyQualifiedContractName", c["name"]),
        "deploymentTransactionHash": None if external else (manifest.get("transactions", {}).get(c["name"]) if isinstance(manifest.get("transactions"), dict) else None),
        "etherscanLink": c.get("etherscanUrl", f"https://etherscan.io/address/{c['address']}"),
        "verificationStatus": verification_status(c, ev, external),
        "verifiedEvidence": bool(ev.get("verified")) if not external else False,
        "etherscanStatus": ev.get("etherscanStatus"),
        "runtimeCodePresent": ev.get("runtimeCodePresent"),
        "runtimeCodeHash": c.get("runtimeCodeHash"),
        "ownerCoverage": c.get("ownerCoverage"),
        "interfaceCoverage": c.get("interfaceCoverage"),
    }

entries = [entry(c) for c in contracts]
goalos_entries = [e for e in entries if not e["external"]]
operator_verified = sum(1 for e in goalos_entries if e["verifiedEvidence"])
reg = {
    "metadata": {
        "packageVersion": "4.4.0",
        "network": "Ethereum Mainnet",
        "chainId": 1,
        "releaseTag": TAG,
        "releaseTagSha": SHA,
        "deploymentPath": "DIRECT_OPERATOR_NO_CERTIFICATE",
        "generatedFrom": [
            "deployments/ethereum-mainnet.agialpha.latest.json",
            "qa/mainnet-release-state.json",
            "qa/mainnet-postdeploy/verification-evidence.json",
            "qa/mainnet-postdeploy/runtime-bytecode-report.json",
        ],
        "operatorVerificationEvidence": f"{operator_verified}/48",
        "runtimeBytecodeStatus": runtime_report.get("status"),
        "providerComparison": runtime_report.get("providerComparison"),
        "productionActivation": "NO",
        "userFundAuthorization": "NO",
        "claimBoundary": "Verification status values are copied from evidence files; seed/API-refresh and live-RPC-validation qualifiers are preserved and not promoted to unconditional pass.",
    },
    "contracts": entries,
}

def write(path, content):
    dest = ROOT / path
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content)

write(pathlib.Path("config/ethereum-mainnet.contracts.json"), json.dumps(reg, indent=2) + "\n")
write(pathlib.Path("website/data/ethereum-mainnet.contracts.json"), json.dumps(reg, indent=2) + "\n")
write(pathlib.Path("app/config/ethereum-mainnet.contracts.generated.ts"), "/* Generated by scripts/generate_mainnet_docs.py. Do not edit manually. */\nexport const ethereumMainnetContracts = " + json.dumps(reg, indent=2) + " as const;\n")
rows = "\n".join(
    f"| {e['name']} | `{e['address']}` | {'External canonical AGIALPHA' if e['external'] else 'GoalOS-created'} | {e['verificationStatus']} | {e.get('runtimeCodePresent') or 'n/a'} | [Etherscan]({e['etherscanLink']}) |"
    for e in entries
)
write(pathlib.Path("docs/ETHEREUM_MAINNET_CONTRACTS.md"), f"""# Ethereum Mainnet Contract Registry

Status: GENERATED

Generated from `deployments/ethereum-mainnet.agialpha.latest.json`, `qa/mainnet-release-state.json`, `qa/mainnet-postdeploy/verification-evidence.json`, and `qa/mainnet-postdeploy/runtime-bytecode-report.json`. Do not edit manually; run `npm run mainnet:contracts:generate`.

| Metric | Value |
| --- | --- |
| Total entries | 49 |
| GoalOS-created contracts | 48 |
| External entries | 1 |
| Chain ID | 1 |
| Operator verification evidence | {operator_verified}/48 GoalOS contracts |
| Runtime bytecode status | {runtime_report.get('status') or 'UNKNOWN'} |
| Provider comparison | {runtime_report.get('providerComparison') or 'UNKNOWN'} |
| Production activation | NO |
| User-fund authorization | NO |

Verification status values below are copied from the evidence file. Qualifiers such as `verified_from_seed_requires_api_refresh` and `requires mainnet:postdeploy:revalidate` are preserved and must not be promoted to unconditional independent verification or live-RPC bytecode validation.

| Name | Address | Boundary | Verification evidence status | Runtime code evidence | Link |
| --- | --- | --- | --- | --- | --- |
{rows}
""")
