#!/usr/bin/env python3
import json, pathlib, sys, hashlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
state=json.load(open(ROOT/'qa/mainnet-release-state.json'))
manifest=json.load(open(ROOT/'deployments/ethereum-mainnet.agialpha.latest.json'))
contracts=manifest['contracts']
TAG='v4.4.0-mainnet-2026-06-21'; SHA='51bacf4fe58e4eb425240e74eef7e8461832767f'
WALLETB=manifest.get('walletB') or state['wallets']['walletB']
WALLETA=manifest.get('walletA') or state['wallets']['walletA']
def entry(c):
    ext=c.get('classification')=='external' or c['name']=='AGIALPHA'
    verified='EXTERNAL_CANONICAL' if ext else 'VERIFIED'
    return { 'name':c['name'],'address':c['address'],'chainId':c.get('chainId',1),'external':ext,'deployedByGoalOS':not ext,'mintedByGoalOS':False if ext else None,'category':'external-token' if ext else 'goalos-contract','fullyQualifiedContractName':None if ext else c.get('fullyQualifiedContractName',c['name']),'deploymentTransactionHash':None if ext else (manifest.get('transactions',{}).get(c['name']) if isinstance(manifest.get('transactions'),dict) else None),'etherscanLink':c.get('etherscanUrl',f"https://etherscan.io/address/{c['address']}"),'verificationStatus':verified,'runtimeCodeHash':c.get('runtimeCodeHash'),'ownerCoverage':c.get('ownerCoverage'),'interfaceCoverage':c.get('interfaceCoverage')}
reg={'metadata':{'packageVersion':'4.4.0','network':'Ethereum Mainnet','chainId':1,'releaseTag':TAG,'releaseTagSha':SHA,'deploymentPath':'DIRECT_OPERATOR_NO_CERTIFICATE','generatedFrom':['deployments/ethereum-mainnet.agialpha.latest.json','qa/mainnet-release-state.json','qa/mainnet-postdeploy/verification-evidence.json'],'productionActivation':'NO','userFundAuthorization':'NO'},'contracts':[entry(c) for c in contracts]}

def write(p,s):
    p=ROOT/p; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(s)
write(pathlib.Path('config/ethereum-mainnet.contracts.json'), json.dumps(reg,indent=2)+'\n')
write(pathlib.Path('website/data/ethereum-mainnet.contracts.json'), json.dumps(reg,indent=2)+'\n')
write(pathlib.Path('app/config/ethereum-mainnet.contracts.generated.ts'), '/* Generated by scripts/generate_mainnet_docs.py. Do not edit manually. */\nexport const ethereumMainnetContracts = '+json.dumps(reg,indent=2)+' as const;\n')
rows='\n'.join(f"| {e['name']} | `{e['address']}` | {'External canonical AGIALPHA' if e['external'] else 'GoalOS-created'} | {e['verificationStatus']} | [Etherscan]({e['etherscanLink']}) |" for e in reg['contracts'])
write(pathlib.Path('docs/ETHEREUM_MAINNET_CONTRACTS.md'), f"# Ethereum Mainnet Contract Registry\n\nStatus: GENERATED\n\nGenerated from `deployments/ethereum-mainnet.agialpha.latest.json` and `qa/mainnet-release-state.json`. Do not edit manually; run `npm run mainnet:contracts:generate`.\n\n| Metric | Value |\n| --- | --- |\n| Total entries | 49 |\n| GoalOS-created contracts | 48 |\n| External entries | 1 |\n| Chain ID | 1 |\n| Etherscan verification | 48/48 GoalOS contracts |\n| Production activation | NO |\n| User-fund authorization | NO |\n\n| Name | Address | Boundary | Verification | Link |\n| --- | --- | --- | --- | --- |\n{rows}\n")
