#!/usr/bin/env python3
from __future__ import annotations
import json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
cert=json.loads((ROOT/'qa/mainnet-authorization-certificate.json').read_text())
tech=cert['technicallyMainnetReady']; dep=cert['mainnetDeploymentAuthorized']; eth=cert['ethereumMainnetAuthorized']; deployed=cert['mainnetDeployed']
status_block=f"""GoalOS AGIALPHA Ascension v4.4 mainnet authorization candidate.

Automated/internal security toolchain: passed.
Local deterministic rehearsal: passed.
Local Evidence Docket: generated.
Public AGIALPHA token verification: passed / governance-accepted.
Not externally audited.
Ethereum Mainnet technical readiness: {tech}.
Ethereum Mainnet deployment authorization: {dep}.
Ethereum Mainnet authorization: {eth}.
Ethereum Mainnet deployed: {deployed}.

This means the repository package is authorized for manual gated Ethereum Mainnet deployment. It does not mean Ethereum Mainnet deployment has occurred. Actual deployment still requires a runtime RPC URL and deployer key outside GitHub.

It does not claim external audit completion, legal approval, tax review, guaranteed security, guaranteed token classification, investment return, yield, price target, revenue share, or production deployment.
"""
readme=f"""# GoalOS AGIALPHA Ascension

{status_block}

## Core doctrine

- GoalOS decides what may evolve.
- AGIALPHA coordinates proof-settled work.
- Evidence Dockets make claims auditable.
- Do not put intelligence on-chain; put proof of intelligence on-chain.
- No proof, no evolution. No eval, no propagation. No rollback, no release.

## Ethereum Mainnet authorization

The source of truth is `qa/mainnet-authorization-certificate.json`. README/status documents are generated from that certificate; manual edits cannot create YES.

- TECHNICALLY_MAINNET_READY: **{tech}**
- MAINNET_DEPLOYMENT_AUTHORIZED: **{dep}**
- ETHEREUM_MAINNET_AUTHORIZED: **{eth}**
- MAINNET_DEPLOYED: **{deployed}**
- Canonical AGIALPHA token: `{cert['agialphaToken']}`
- Chain: Ethereum Mainnet (`chainId=1`)
- Final manual command: `npm run deploy:ethereum-mainnet:gated`

## Safety boundary

CI cannot deploy Ethereum Mainnet. Runtime RPC URL, deployer key, and runtime addresses are local broadcast inputs only and are not stored in GitHub. MockAGIALPHA is local/Sepolia-only and is forbidden on Ethereum Mainnet. No new AGIALPHA token is deployed on Ethereum Mainnet.
"""
(ROOT/'README.md').write_text(readme)
(ROOT/'docs/CURRENT_STATUS.md').write_text('# Current Status\n\n'+status_block+f"\n## Certificate source\n\n`qa/mainnet-authorization-certificate.json` generated by `{cert['generatedBy']}` at `{cert['generatedAt']}`.\n")
(ROOT/'docs/MAINNET_AUTHORIZATION_CERTIFICATE.md').write_text(f"""# Mainnet Authorization Certificate

Generated from `qa/mainnet-authorization-certificate.json`.

- TECHNICALLY_MAINNET_READY: **{tech}**
- MAINNET_DEPLOYMENT_AUTHORIZED: **{dep}**
- ETHEREUM_MAINNET_AUTHORIZED: **{eth}**
- MAINNET_DEPLOYED: **{deployed}**
- Private operator authorization package required: **{cert['privateOperatorAuthorizationPackageRequired']}**
- Runtime secrets stored in GitHub: **{cert['runtimeSecretsStoredInGitHub']}**
- CI can deploy mainnet: **{cert['ciCanDeployMainnet']}**

This certificate authorizes only manual, local, gated Ethereum Mainnet deployment. It is not an external audit, legal approval, tax review, proof of deployment, or guarantee of security/token classification.

## Next action

{cert['nextAction']}
""")
(ROOT/'docs/START_HERE_MAINNET.md').write_text(f"""# Start Here: Ethereum Mainnet

{status_block}

## Command center

1. Check public repo status: `npm run mainnet:status`
2. Run local public checks: `npm run mainnet:local-checks`
3. Run automated/internal security toolchain: `npm run mainnet:security`
4. Run local deterministic rehearsal: `npm run mainnet:local-rehearsal`
5. Run public AGIALPHA token verification: `npm run verify:agialpha-token:public`
6. Generate Mainnet Authorization Certificate: `npm run mainnet:certificate`
7. Compute technical readiness: `npm run mainnet:readiness-check`
8. Compute deployment authorization: `npm run mainnet:deployment-authorization-check`
9. Compute Ethereum Mainnet authorization: `npm run mainnet:authorization-check`
10. Show final manual deployment command: `npm run mainnet:next`
11. Run final local gated deployment: `npm run deploy:ethereum-mainnet:gated`
12. Generate post-deployment report after real transaction evidence exists.
""")
print('Generated public status docs from qa/mainnet-authorization-certificate.json')
