import fs from "fs";
import crypto from "crypto";
import { ethers } from "ethers";
import { loadDeploymentEnv } from "../config/loadEnv";
import { AGIALPHA_MAINNET_TOKEN, getExpectedChainId, getOptionalPrivateKey, getOptionalRpcUrl } from "../config/networkConfig";
import { redactString, REDACTED } from "./lib/redact";

export const CLAIM_BOUNDARY = "This evidence reports deployment mechanics only. It does not claim achieved AGI, ASI, superintelligence, guaranteed ROI, legal approval, tax approval, security approval, external audit completion, production safety, or Ethereum Mainnet deployment.";
const CONFIRM = "DEPLOY_GOALOS_AGIALPHA_ASCENSION_TO_ETHEREUM_MAINNET";
type Check = { name: string; status: "PASS"|"WARN"|"FAIL"; value?: string; nextAction?: string };
function arg(name: string) { const i=process.argv.indexOf(name); return i>=0 ? process.argv[i+1] : undefined; }
function has(name: string) { return process.argv.includes(name); }
function networkFromArgs(action: string) { return arg("--network") || (action.includes("mainnet") ? "ethereumMainnet" : action.includes("sepolia") ? "ethereumSepolia" : "ethereumSepolia"); }
function ok(s:string){return process.stdout.isTTY?`\x1b[32m${s}\x1b[0m`:s} function warn(s:string){return process.stdout.isTTY?`\x1b[33m${s}\x1b[0m`:s} function bad(s:string){return process.stdout.isTTY?`\x1b[31m${s}\x1b[0m`:s}
function renderStatus(s:string){return s==="PASS"?ok("PASS"):s==="WARN"?warn("WARN"):bad("FAIL")}
function shaFile(p:string){return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")}
function safeProviderName(url?: string){ if(!url) return "not configured"; try { const h=new URL(redactString(url)); return h.hostname; } catch { return url ? REDACTED : "not configured"; }}
export function requiredManifestContractsComplete(m:any): boolean { const entries = Array.isArray(m.manifestContracts) ? m.manifestContracts : (Array.isArray(m.contractsArray) ? m.contractsArray : []); const requiredEntries = entries.filter((c:any)=>c?.verification?.status !== "skipped"); return entries.length > 0 && requiredEntries.length > 0 && requiredEntries.every((c:any)=>typeof c.txHash === "string" && /^0x[0-9a-fA-F]{64}$/.test(c.txHash) && c.bytecodePresent === true); }
function manifestTransactionHashes(m:any): string[] { const source=m.transactionHashes ?? m.transactions ?? []; if(Array.isArray(source)) return source.map((entry:any)=>typeof entry==="string"?entry:(entry?.hash||entry?.transactionHash||"")).filter(Boolean); if(source && typeof source==="object") return Object.values(source).map(String).filter(Boolean); return []; }
export function assertMainnetEvidenceManifest(m:any): void { const txHashes=manifestTransactionHashes(m); if(m.status !== "complete" || Number(m.chainId) !== 1 || !txHashes.length || !m.contracts || !Object.keys(m.contracts).length || !requiredManifestContractsComplete(m)) throw new Error("Mainnet evidence blocked: manifest must be complete and include real chainId=1 per-contract tx evidence. Mainnet deployed remains NO."); }
async function doctor(networkName:string): Promise<{networkName:string; expected:number; detected?:number; checks:Check[]; allowedNextStep:string}> {
 loadDeploymentEnv(networkName); const expected=getExpectedChainId(networkName); const rpc=getOptionalRpcUrl(networkName); const key=getOptionalPrivateKey(networkName); const checks:Check[]=[];
 checks.push({name:"RPC configured",status:rpc?"PASS":"FAIL",value:rpc?safeProviderName(rpc):"missing",nextAction:rpc?undefined:`Set ${networkName.includes("Mainnet")?"PRIVATE_MAINNET_RPC_URL":"PRIVATE_SEPOLIA_RPC_URL"}.`});
 checks.push({name:"Deployer key configured",status:key?/^0x[0-9a-fA-F]{64}$/.test(key)?"PASS":"FAIL":"FAIL",value:key?"configured/redacted":"missing",nextAction:key?(/^0x[0-9a-fA-F]{64}$/.test(key)?undefined:"Use a 0x-prefixed 64-hex-character private key."):`Set ${networkName.includes("Mainnet")?"PRIVATE_MAINNET_DEPLOYER_PRIVATE_KEY":"PRIVATE_SEPOLIA_DEPLOYER_PRIVATE_KEY"}.`});
 let detected: number|undefined, addr="unavailable", bal="unavailable", nonce="unavailable";
 if(rpc){ try{ const provider=new ethers.JsonRpcProvider(rpc); detected=Number((await provider.getNetwork()).chainId); checks.push({name:"Chain ID detected",status:detected===expected?"PASS":"FAIL",value:String(detected),nextAction:detected===expected?undefined:`Fix RPC/network. Expected ${expected} for ${networkName}.`}); if(key && /^0x[0-9a-fA-F]{64}$/.test(key)){ const w=new ethers.Wallet(key,provider); addr=w.address; bal=ethers.formatEther(await provider.getBalance(addr)); nonce=String(await provider.getTransactionCount(addr)); const min=networkName.includes("Mainnet")?"0.50":"0.10"; checks.push({name:"Deployer balance",status:Number(bal)>=Number(min)?"PASS":"WARN",value:`${bal} ETH`,nextAction:Number(bal)>=Number(min)?undefined:`Fund deployer with at least about ${min} ETH before live broadcast.`}); }}catch(e:any){ checks.push({name:"Chain ID detected",status:"FAIL",value:"unavailable",nextAction:`Check RPC URL; provider error: ${e.message}`}); }}
 checks.push({name:"Deployer address",status:addr==="unavailable"?"WARN":"PASS",value:addr}); checks.push({name:"Nonce",status:nonce==="unavailable"?"WARN":"PASS",value:nonce}); checks.push({name:"Etherscan API configured",status:process.env.ETHERSCAN_API_KEY?"PASS":"WARN",value:process.env.ETHERSCAN_API_KEY?"configured/redacted":"missing",nextAction:process.env.ETHERSCAN_API_KEY?undefined:"Set ETHERSCAN_API_KEY before verify commands."});
 checks.push({name:"Sourcify configured",status:(process.env.SOURCIFY_ENABLED||"true")!=="false"?"PASS":"WARN",value:(process.env.SOURCIFY_ENABLED||"true")});
 checks.push({name:"Compiler",status:fs.existsSync("hardhat.config.ts")?"PASS":"FAIL",value:"Solidity 0.8.35"});
 checks.push({name:"Hardhat",status:fs.existsSync("package.json")?"PASS":"FAIL",value:"2.28.6"});
 checks.push({name:"Tests",status:fs.existsSync("test/deploymentUxSafety.test.ts")?"PASS":"WARN",value:"deployment UX safety tests present"});
 checks.push({name:"Static checks",status:fs.existsSync("scripts/static_check.py")?"PASS":"WARN",value:"npm run static-check"});
 const manifest=networkName.includes("Mainnet")?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json"; const manifestExists=fs.existsSync(manifest); const manifestData=manifestExists?JSON.parse(fs.readFileSync(manifest,"utf8")):null; checks.push({name:"Deployment manifest",status:manifestExists?"PASS":"WARN",value:manifest,nextAction:manifestExists?undefined:`Run ${networkName.includes("Mainnet")?"npm run deploy:mainnet:live-local-gated":"npm run deploy:sepolia:live"} after readiness passes.`});
 checks.push({name:"Manifest hash",status:manifestExists?"PASS":"WARN",value:manifestExists?shaFile(manifest):"missing"});
 checks.push({name:"AGIALPHA token",status:manifestData?.agialphaToken||process.env.AGIALPHA_TOKEN_ADDRESS?"PASS":"WARN",value:manifestData?.agialphaToken||process.env.AGIALPHA_TOKEN_ADDRESS||"missing"});
 checks.push({name:"Canonical AGIALPHA token",status:networkName.includes("Mainnet")?(manifestData?.agialphaToken===AGIALPHA_MAINNET_TOKEN||process.env.AGIALPHA_TOKEN_ADDRESS===AGIALPHA_MAINNET_TOKEN?"PASS":"FAIL"):"WARN",value:networkName.includes("Mainnet")?AGIALPHA_MAINNET_TOKEN:"Sepolia may use mock or explicit rehearsal token"});
 checks.push({name:"Mock token used",status:manifestData?.mockAgialphaUsed?"WARN":"PASS",value:String(Boolean(manifestData?.mockAgialphaUsed))});
 checks.push({name:"New AGIALPHA token deployment",status:manifestData?.newAgialphaTokenDeployed?"FAIL":"PASS",value:String(Boolean(manifestData?.newAgialphaTokenDeployed))});
 checks.push({name:"Contract addresses",status:manifestData?.contracts&&Object.keys(manifestData.contracts).length?"PASS":"WARN",value:String(manifestData?.contracts?Object.keys(manifestData.contracts).length:0)});
 checks.push({name:"Bytecode present",status:manifestData?.manifestContracts?.every?.((c:any)=>c.bytecodePresent)?"PASS":"WARN",value:manifestData?.manifestContracts?"recorded in manifest":"unchecked"});
 checks.push({name:"Constructor args recorded",status:(manifestData?.constructorArgs&&Object.keys(manifestData.constructorArgs).length)||manifestData?.manifestContracts?.every?.((c:any)=>Array.isArray(c.constructorArgs))?"PASS":"WARN",value:manifestData?"recorded or required for verification":"missing manifest"});
 checks.push({name:"Explorer verification",status:manifestData?.verificationStatus==="VERIFIED"?"PASS":"WARN",value:manifestData?.verificationStatus||"pending/not run"});
 checks.push({name:"Already verified",status:"WARN",value:"see verification evidence"});
 checks.push({name:"Failed verification",status:"WARN",value:"see verification evidence"});
 checks.push({name:"Claim boundary",status:"PASS",value:"evidence-first/no marketing claims"});
 const evidence=networkName.includes("Mainnet")?"qa/mainnet-deployment-evidence.json":"qa/sepolia-deployment-evidence.json"; checks.push({name:"Evidence files",status:fs.existsSync(evidence)?"PASS":"WARN",value:evidence,nextAction:fs.existsSync(evidence)?undefined:`Run ${networkName.includes("Mainnet")?"npm run deploy:mainnet:evidence":"npm run deploy:sepolia:evidence"}.`});
 if(networkName.includes("Mainnet")){ const token=process.env.AGIALPHA_TOKEN_ADDRESS; checks.push({name:"Authorization gates",status:(process.env.ALLOW_MAINNET_DEPLOYMENT&&process.env.MAINNET_DEPLOYMENT_CONFIRMATION)?"PASS":"WARN",value:"local-only typed gates required"}); checks.push({name:"Mainnet canonical AGIALPHA",status:token===AGIALPHA_MAINNET_TOKEN?"PASS":"FAIL",value:token||"missing",nextAction:`Set AGIALPHA_TOKEN_ADDRESS=${AGIALPHA_MAINNET_TOKEN}.`}); checks.push({name:"CI mainnet broadcast gate",status:(process.env.CI||process.env.GITHUB_ACTIONS)?"FAIL":"PASS",value:(process.env.CI||process.env.GITHUB_ACTIONS)?"blocked in CI":"local shell",nextAction:"Final Mainnet broadcast must be local-only."}); checks.push({name:"Typed confirmation",status:process.env.MAINNET_DEPLOYMENT_CONFIRMATION===CONFIRM?"PASS":"WARN",value:process.env.MAINNET_DEPLOYMENT_CONFIRMATION?"provided/redacted":"missing",nextAction:`Set MAINNET_DEPLOYMENT_CONFIRMATION=${CONFIRM} only for final local deploy.`}); }
 const fail=checks.find(c=>c.status==="FAIL"); return {networkName, expected, detected, checks, allowedNextStep: fail?`Fix: ${fail.nextAction}`:(networkName.includes("Mainnet")?"npm run deploy:mainnet:preflight":"npm run deploy:sepolia:dry-run")}; }
function print(d:any){ if(has("--json")) console.log(JSON.stringify(d,null,2)); else { console.log("\nGoalOS Deployment + Verification Command Center\n"); console.log(`Network: ${d.networkName}`); console.log(`Expected chainId: ${d.expected}`); console.log(`Detected chainId: ${d.detected ?? "unknown"}`); for(const c of d.checks){ console.log(`${renderStatus(c.status)} ${c.name}: ${c.value ?? ""}`); if(c.nextAction) console.log(`  Next action: ${c.nextAction}`);} console.log(`Allowed next step: ${d.allowedNextStep}`); }}
function writeMainnetPackage(){ fs.mkdirSync(".private",{recursive:true}); fs.writeFileSync(".private/mainnet-operator.env.template", fs.readFileSync(".env.mainnet.example")); fs.writeFileSync(".private/mainnet-final-command.txt", "source .private/mainnet-operator.env\nnpm run deploy:mainnet:live-local-gated\nnpm run verify:mainnet:all\nnpm run deploy:mainnet:evidence\n"); fs.writeFileSync(".private/mainnet-verification-command.txt", "source .private/mainnet-operator.env\nnpm run verify:mainnet:all\n"); fs.writeFileSync(".private/mainnet-post-deploy-evidence-checklist.md", `# Mainnet post-deploy evidence checklist\n\n- Confirm chainId=1 in the deployment manifest.\n- Confirm every tx hash is real and has code at the deployed address.\n- Run npm run verify:mainnet:all.\n- Run npm run deploy:mainnet:evidence only after real broadcast evidence exists.\n- Stop safely if any check fails; do not claim Mainnet deployed YES.\n`); fs.writeFileSync(".private/mainnet-operator-checklist.md", `# Mainnet local operator checklist\n\nDo not commit this directory. Fill .private/mainnet-operator.env from the template. Confirm MAINNET_TARGET=ethereum, AGIALPHA_TOKEN_ADDRESS=${AGIALPHA_MAINNET_TOKEN}, and type ${CONFIRM} only when ready. Ethereum Mainnet final broadcast is local-only and never CI.\n`); fs.writeFileSync(".private/mainnet-preflight-summary.redacted.json", JSON.stringify({generatedAt:new Date().toISOString(), mainnetDeployed:"NO", ciCanDeployMainnet:false, finalBroadcast:"local-only", agialphaToken:AGIALPHA_MAINNET_TOKEN, claimBoundary:CLAIM_BOUNDARY},null,2)+"\n"); console.log("Generated .private local operator package (redacted templates only)."); }
function evidence(networkName:string){ const main=networkName.includes("Mainnet"); const manifest=main?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json"; if(main && !fs.existsSync(manifest)) throw new Error("Mainnet evidence blocked: no real chainId=1 deployment manifest exists. Mainnet deployed remains NO."); const m=fs.existsSync(manifest)?JSON.parse(fs.readFileSync(manifest,"utf8")):{network:"ethereum-sepolia",chainId:11155111,contracts:{},transactions:[],verificationStatus:"NOT_RUN"}; const txHashes=manifestTransactionHashes(m); if(main) assertMainnetEvidenceManifest(m); const hash=fs.existsSync(manifest)?shaFile(manifest):"manifest-not-yet-generated"; if(fs.existsSync(manifest)) fs.writeFileSync(manifest.replace(/\.json$/, ".sha256"), hash+"\n"); const out={networkName:m.network||networkName,chainId:m.chainId, deployerPublicAddress: main ? (m.deployerCommitmentHash?"commitment:"+m.deployerCommitmentHash:String(m.deployer||"redacted-or-not-yet-deployed")) : "public-deployer-recorded-in-manifest", rpcProviderName:safeProviderName(getOptionalRpcUrl(networkName)), timestamp:new Date().toISOString(), gitCommit:process.env.GITHUB_SHA||"local", packageVersion:JSON.parse(fs.readFileSync("package.json","utf8")).version, solidityCompilerVersion:"0.8.35", hardhatVersion:"2.28.6", agialphaTokenAddress: main ? (m.agialphaToken||AGIALPHA_MAINNET_TOKEN) : "public-token-recorded-in-manifest", mockTokenUsed:!!m.mockAgialphaUsed, newAgialphaTokenDeployed:!!m.newAgialphaTokenDeployed, deployedContractAddresses: main ? (m.contracts||{}) : Object.fromEntries(Object.keys(m.contracts||{}).map((name)=>[name,"public-address-recorded-in-manifest"])), transactionHashes: main ? txHashes : txHashes.map(()=>"public-transaction-hash-recorded-in-manifest"), gasUsedOrEstimated:m.gasUsed||m.estimatedGas||"not recorded", verificationStatus:m.verificationStatus||"NOT_RUN", manifestHash:hash, postDeploymentChecks:[], claimBoundary:CLAIM_BOUNDARY, nextRecommendedAction: main?"Run npm run deploy:mainnet:verify after real local broadcast.":"Run npm run deploy:sepolia:verify if not already verified."}; fs.mkdirSync("qa",{recursive:true}); fs.mkdirSync("docs",{recursive:true}); const q=main?"qa/mainnet-deployment-evidence.json":"qa/sepolia-deployment-evidence.json"; const r=main?"docs/ETHEREUM_MAINNET_DEPLOYMENT_REPORT.md":"docs/SEPOLIA_DEPLOYMENT_REPORT.md"; fs.writeFileSync(q,JSON.stringify(out,null,2)+"\n"); fs.writeFileSync(r,`# ${main?"Ethereum Mainnet":"Sepolia"} Deployment Report\n\nMainnet deployed: ${main?"NO unless this report was generated from a real chainId=1 manifest with transactions":"N/A"}\n\nManifest hash: ${hash}\n\nClaim boundary: ${CLAIM_BOUNDARY}\n`); console.log(`Wrote ${q} and ${r}`); }
async function main(){ const action=process.argv[2]||"doctor"; const networkName=networkFromArgs(action); loadDeploymentEnv(networkName); if(action.includes("prepare-local")){writeMainnetPackage();return;} if(action.includes("evidence")){evidence(networkName);return;} if(action.includes("status")||action.includes("next")||action.includes("doctor")||action.includes("preflight")||action.includes("dry-run")||action.includes("fork-rehearsal")){ print(await doctor(networkName)); return;} throw new Error(`Unknown command-center action: ${action}`); }
if (require.main === module) main().catch(e=>{console.error(e.message||e);process.exitCode=1});
