import fs from "fs";
import path from "path";
import crypto from "crypto";
import readline from "readline";
import { spawnSync } from "child_process";

const MAINNET_TOKEN = "0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA";
type Network = "sepolia" | "mainnet";
type State = "NOT_CONFIGURED" | "CONFIGURED" | "DOCTOR_BLOCKED" | "DOCTOR_PASSED" | "PLAN_CREATED" | "REHEARSAL_BLOCKED" | "REHEARSAL_PASSED" | "AWAITING_BROADCAST_CONFIRMATION" | "BROADCAST_IN_PROGRESS" | "DEPLOYMENT_INTERRUPTED" | "DEPLOYED_PENDING_CONFIRMATIONS" | "DEPLOYED_PENDING_VERIFICATION" | "DEPLOYED_PENDING_OWNER_TRANSFER" | "DEPLOYED_PENDING_OWNER_ACCEPTANCE" | "DEPLOYED_PENDING_ROLE_CLEANUP" | "DEPLOYED_PENDING_CANARY" | "OPERATIONALLY_COMPLETE" | "FAILED_RECOVERABLE" | "FAILED_ENGINEERING_REVIEW_REQUIRED";

type Args = { command: string; network?: Network; json: boolean; nonInteractive: boolean; plan?: string; manifest?: string; debug: boolean };

function parse(): Args {
  const argv = process.argv.slice(2);
  const command = (argv[0] === "--help" || argv.includes("--help")) ? "help" : (argv[0] || "menu");
  const readOpt = (name: string) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : undefined; };
  const networkRaw = readOpt("--network") || (command === "sepolia" ? "sepolia" : command === "mainnet" ? "mainnet" : undefined);
  return { command, network: networkRaw === "mainnet" ? "mainnet" : networkRaw === "sepolia" ? "sepolia" : undefined, json: argv.includes("--json"), nonInteractive: argv.includes("--non-interactive"), plan: readOpt("--plan"), manifest: readOpt("--manifest"), debug: argv.includes("--debug") };
}
function color(code: string, text: string) { return process.env.NO_COLOR ? text : `\x1b[${code}m${text}\x1b[0m`; }
function pass(s: string) { return color("32", s); } function warn(s: string) { return color("33", s); } function blocked(s: string) { return color("31", s); }
function shaJson(obj: unknown) { return "0x" + crypto.createHash("sha256").update(JSON.stringify(obj)).digest("hex"); }
function ensureDir(p: string) { fs.mkdirSync(p, { recursive: true }); }
function run(cmd: string, args: string[], json = false) { const res = spawnSync(cmd, args, { encoding: "utf8", stdio: json ? "pipe" : "inherit" }); return res; }
function networkName(network: Network) { return network === "mainnet" ? "ethereumMainnet" : "ethereumSepolia"; }
function releaseId(network: Network) { return `${network}-${new Date().toISOString().replace(/[:.]/g, "-")}`; }
function publicConfigPath(network: Network) { return `config/deployment/${network}.json`; }
function privateEnvPath(network: Network) { return `.private/${network}-operator.env`; }
function defaultConfig(network: Network) { return { schemaVersion: "1.0", network, expectedChainId: network === "mainnet" ? 1 : 11155111, agialphaToken: network === "mainnet" ? MAINNET_TOKEN : "CONFIGURE_EXISTING_OR_SEPOLIA_MOCK", finalOwnerKind: "SAFE", finalOwnerAddress: "0x0000000000000000000000000000000000000000", confirmations: network === "mainnet" ? 5 : 2, gasBudgetEthCeiling: network === "mainnet" ? "1.0" : "0.2", canaryLimits: { maxProtectedLiabilityPerToken: "0", maxSingleReward: "0" }, topologyVersion: "goalos-agialpha-ascension-v4.4.0", claimBoundary: "Configuration only; no deployment evidence." }; }
function writeSetup(network: Network) { ensureDir("config/deployment"); ensureDir(".private"); const cfg = publicConfigPath(network); if (!fs.existsSync(cfg)) fs.writeFileSync(cfg, JSON.stringify(defaultConfig(network), null, 2) + "\n"); const env = privateEnvPath(network); if (!fs.existsSync(env)) { const rpc = network === "mainnet" ? "PRIVATE_MAINNET_RPC_URL" : "PRIVATE_SEPOLIA_RPC_URL"; const key = network === "mainnet" ? "PRIVATE_MAINNET_DEPLOYER_PRIVATE_KEY" : "PRIVATE_SEPOLIA_DEPLOYER_PRIVATE_KEY"; fs.writeFileSync(env, `# GoalOS ${network} private operator file. Do not commit.\n${rpc}=\n${key}=\nETHERSCAN_API_KEY=\n`); try { fs.chmodSync(env, 0o600); } catch {} } return { status: "PASS", config: cfg, privateEnv: env, next: `npm run deploy:doctor -- --network ${network}` }; }
function loadConfig(network: Network) { const p = publicConfigPath(network); if (!fs.existsSync(p)) return undefined; return JSON.parse(fs.readFileSync(p, "utf8")); }
function status(network: Network): { state: State; passed: string[]; missing: string[]; transactionSent: boolean; safeToResume: boolean; next: string } { const cfg = loadConfig(network); const plansDir = `deployments/plans/${network}`; const manifestsDir = `deployments/${network}`; const plans = fs.existsSync(plansDir) ? fs.readdirSync(plansDir).filter(f => f.endsWith(".plan.json")) : []; const manifests = fs.existsSync(manifestsDir) ? fs.readdirSync(manifestsDir).filter(f => f === "manifest.json" || f.endsWith("manifest.json")) : []; const passed: string[] = []; const missing: string[] = []; if (cfg) passed.push("public configuration"); else missing.push("public configuration"); if (fs.existsSync(privateEnvPath(network))) passed.push("private operator template"); else missing.push("private operator file"); if (plans.length) passed.push("immutable plan"); else missing.push("immutable plan"); if (manifests.length) passed.push("deployment manifest"); else missing.push("deployment manifest"); const state: State = !cfg ? "NOT_CONFIGURED" : manifests.length ? "DEPLOYED_PENDING_VERIFICATION" : plans.length ? "PLAN_CREATED" : "CONFIGURED"; const next = !cfg ? `npm run deploy:setup -- --network ${network}` : !plans.length ? `npm run deploy:plan -- --network ${network}` : !manifests.length ? `npm run deploy:rehearse -- --network ${network} --plan deployments/plans/${network}/${plans[plans.length - 1]}` : `npm run deploy:verify -- --manifest deployments/${network}/manifest.json`; return { state, passed, missing, transactionSent: manifests.length > 0, safeToResume: ["BROADCAST_IN_PROGRESS", "DEPLOYED_PENDING_VERIFICATION"].includes(state), next }; }
function plan(network: Network) { const cfg = loadConfig(network); if (!cfg) throw new Error(`Missing ${publicConfigPath(network)}. Run npm run deploy:setup -- --network ${network}.`); if (network === "mainnet" && cfg.agialphaToken !== MAINNET_TOKEN) throw new Error("Mainnet plan blocked: canonical AGIALPHA token mismatch."); const id = releaseId(network); const dir = `deployments/plans/${network}`; ensureDir(dir); const body = { schemaVersion: "1.0", releaseId: id, network, chainId: cfg.expectedChainId, configHash: shaJson(cfg), commit: spawnSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).stdout.trim(), agialphaToken: cfg.agialphaToken, finalOwnerKind: cfg.finalOwnerKind, finalOwnerAddress: cfg.finalOwnerAddress, topologyVersion: cfg.topologyVersion, createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 7 * 86400_000).toISOString(), broadcastRequiresTypedConfirmation: network === "mainnet" ? "DEPLOY ETHEREUM MAINNET <last-8-plan-hash>" : "DEPLOY ETHEREUM SEPOLIA <last-8-plan-hash>", noMainnetBroadcastInCI: true, claimBoundary: "Plan only; no transaction sent." }; const hash = shaJson(body); const full = { ...body, planHash: hash }; const jsonPath = `${dir}/${id}.plan.json`; fs.writeFileSync(jsonPath, JSON.stringify(full, null, 2) + "\n"); fs.writeFileSync(`${dir}/${id}.plan.md`, `# GoalOS deployment plan\n\nNetwork: ${network}\n\nPlan hash: ${hash}\n\nNo transaction has been sent.\n`); return { status: "PASS", plan: jsonPath, planHash: hash, next: `npm run deploy:rehearse -- --network ${network} --plan ${jsonPath}` }; }
function rehearse(network: Network, planPath?: string) { if (!planPath || !fs.existsSync(planPath)) throw new Error("Missing --plan <path> for rehearsal."); const p = JSON.parse(fs.readFileSync(planPath, "utf8")); if (p.network !== network) throw new Error("Plan network mismatch."); const report = { schemaVersion: "1.0", status: network === "mainnet" ? "BLOCKED_MAINNET_FORK_RPC_REQUIRED" : "REHEARSAL_PASSED_NO_LIVE_TRANSACTIONS_SENT", network, planHash: p.planHash, generatedAt: new Date().toISOString(), mainnetBroadcastOccurred: false, claimBoundary: network === "mainnet" ? "Mainnet release rehearsal requires protected fork RPC; local stub did not claim fork PASS." : "Local Hardhat rehearsal stub; no public transaction sent." }; const dir = `deployments/${network}/${p.releaseId}`; ensureDir(dir); fs.writeFileSync(`${dir}/rehearsal.json`, JSON.stringify(report, null, 2) + "\n"); return report; }
function evidence(manifestPath?: string) { if (!manifestPath || !fs.existsSync(manifestPath)) throw new Error("Missing --manifest <path>."); const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")); const dir = path.dirname(manifestPath); const ev = { schemaVersion: "1.0", manifestHash: shaJson(manifest), mainnetDeployed: manifest.chainId === 1 && manifest.transactionHashes?.length ? "YES" : "NO", generatedAt: new Date().toISOString(), claimBoundary: "Evidence generated from manifest only; Mainnet YES requires real chainId=1 transactions." }; fs.writeFileSync(`${dir}/evidence.json`, JSON.stringify(ev, null, 2) + "\n"); fs.writeFileSync(`${dir}/REPORT.md`, `# GoalOS deployment report\n\nNetwork: ${manifest.network}\n\nMainnet deployed: ${ev.mainnetDeployed}\n`); fs.writeFileSync(`${dir}/REPORT.html`, `<h1>GoalOS deployment report</h1><p>Mainnet deployed: ${ev.mainnetDeployed}</p>`); return ev; }
function expert(args: Args) { const network = args.network || "sepolia"; if (args.command === "setup") return writeSetup(network); if (["doctor", "sepolia", "mainnet"].includes(args.command)) { const st = status(network); const missingPrivate = !fs.existsSync(privateEnvPath(network)); return { status: missingPrivate ? "BLOCKED" : "PASS", checks: st, exitCode: missingPrivate ? 2 : 0, next: missingPrivate ? `npm run deploy:setup -- --network ${network}` : `npm run deploy:plan -- --network ${network}` }; } if (args.command === "plan") return plan(network); if (args.command === "rehearse") return rehearse(network, args.plan); if (args.command === "status") return status(network); if (args.command === "broadcast") throw new Error(network === "mainnet" ? "Mainnet broadcast requires local typed confirmation and is not implemented in Codex/non-interactive mode." : "Sepolia broadcast adapter requires a reviewed plan and live operator secrets; use existing deploy:sepolia:live after rehearsal."); if (["resume", "verify", "handoff"].includes(args.command)) return { status: args.manifest ? "PASS" : "NEXT_ACTION", handoffState: args.command === "handoff" ? "PENDING_OWNER_TRANSFER" : undefined, next: args.manifest ? `Manifest accepted for ${args.command}; no completion claim made until readback evidence passes.` : `Provide --manifest <path>.` }; if (args.command === "evidence" || args.command === "report") return evidence(args.manifest); if (args.command === "help") return { status: "PASS", usage: "npm run deploy -- [setup|doctor|plan|rehearse|broadcast|resume|verify|handoff|status|evidence|report] -- --network sepolia|mainnet", menu: ["Deploy or rehearse on Sepolia", "Prepare a controlled Ethereum Mainnet deployment", "Resume an interrupted deployment", "Verify an existing deployment", "Complete ownership handoff", "Check current deployment status", "Generate/share a deployment report", "Exit"] }; throw new Error(`Unknown deploy command: ${args.command}`); }
async function menu() { console.log("GoalOS Deployment Command Center\n"); console.log("1. Deploy or rehearse on Sepolia\n2. Prepare a controlled Ethereum Mainnet deployment\n3. Resume an interrupted deployment\n4. Verify an existing deployment\n5. Complete ownership handoff\n6. Check current deployment status\n7. Generate/share a deployment report\n8. Exit\n"); const rl = readline.createInterface({ input: process.stdin, output: process.stdout }); const answer: string = await new Promise(resolve => rl.question("Choose an option: ", resolve)); rl.close(); const network: Network = answer.trim() === "2" ? "mainnet" : "sepolia"; if (answer.trim() === "8") return { status: "EXIT" }; if (answer.trim() === "6") return status(network); if (["1", "2"].includes(answer.trim())) return expert({ command: network, network, json: false, nonInteractive: false, debug: false }); return { status: "NEXT_ACTION", next: "Run npm run deploy:status -- --network sepolia or npm run deploy:resume -- --manifest <path>." }; }
(async () => { const args = parse(); try { const out: any = args.command === "menu" && !args.nonInteractive ? await menu() : expert(args); if (args.json) console.log(JSON.stringify(out, null, 2)); else if (out) { console.log("\n" + (out.status === "PASS" ? pass("PASS") : out.status?.startsWith("BLOCKED") ? blocked(out.status) : warn(out.status || "STATUS"))); console.log(JSON.stringify(out, null, 2)); } } catch (error: any) { if (args.debug) console.error(error); console.error(blocked("BLOCKED"), error.message); process.exitCode = 1; } })();
