import fs from "fs";
import crypto from "crypto";
import { spawnSync } from "child_process";
import { ethers } from "ethers";
import { loadDeploymentEnv } from "../config/loadEnv";
import { AGIALPHA_MAINNET_TOKEN, getExpectedChainId, getOptionalPrivateKey, getOptionalRpcUrl } from "../config/networkConfig";
import { redactString, REDACTED } from "./lib/redact";
import { assertMainnetAuthorizationCertificate } from "./lib/mainnetGuards";

export const CLAIM_BOUNDARY = "This evidence reports Ethereum Mainnet deployment, verification, and configuration mechanics only. It does not claim achieved AGI, ASI, superintelligence, guaranteed ROI, legal approval, tax approval, security approval, external audit completion, production safety, user-fund authorization, or production activation.";
const CONFIRM = "DEPLOY_GOALOS_AGIALPHA_ASCENSION_TO_ETHEREUM_MAINNET";
type Check = { name: string; status: "PASS"|"WARN"|"FAIL"; value?: string; nextAction?: string };
function arg(name: string) { const i=process.argv.indexOf(name); return i>=0 ? process.argv[i+1] : undefined; }
function has(name: string) { return process.argv.includes(name); }
function networkFromArgs(action: string) { return arg("--network") || (action.includes("mainnet") ? "ethereumMainnet" : action.includes("sepolia") ? "ethereumSepolia" : "ethereumSepolia"); }
function ok(s:string){return process.stdout.isTTY?`\x1b[32m${s}\x1b[0m`:s} function warn(s:string){return process.stdout.isTTY?`\x1b[33m${s}\x1b[0m`:s} function bad(s:string){return process.stdout.isTTY?`\x1b[31m${s}\x1b[0m`:s}
function renderStatus(s:string){return s==="PASS"?ok("PASS"):s==="WARN"?warn("WARN"):bad("FAIL")}
function shaFile(p:string){return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")}
function shaText(text:string){return "0x"+crypto.createHash("sha256").update(text).digest("hex")}
function readAuthorityPolicy(){ const p=arg("--policy")||process.env.AUTHORITY_POLICY_PATH||".private/authority-policy.mainnet.json"; return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,"utf8")):undefined; }
function safeProviderName(url?: string){ if(!url) return "not configured"; try { const h=new URL(redactString(url)); return h.hostname; } catch { return url ? REDACTED : "not configured"; }}
function manifestTransactionHashes(m:any): string[] { const source=m.transactionHashes ?? m.transactions ?? []; if(Array.isArray(source)) return source.map((entry:any)=>typeof entry==="string"?entry:(entry?.hash||entry?.transactionHash||"")).filter(Boolean); if(source && typeof source==="object") return Object.values(source).map(String).filter(Boolean); return []; }
function mainnetAuthorizationGateCheck(): Check { const certificate="qa/mainnet-authorization-certificate.json"; try { assertMainnetAuthorizationCertificate(certificate); const validation=spawnSync("python", ["scripts/validate-mainnet-authorization-certificate.py", "--certificate", certificate], {encoding:"utf8"}); if(validation.status!==0){ let detail=(validation.stdout||validation.stderr||"validator failed").trim(); try { const parsed=JSON.parse(validation.stdout||"{}"); detail=(parsed.errors||[]).join("; ") || parsed.status || detail; } catch {} return {name:"Authorization gates",status:"FAIL",value:certificate,nextAction:`Run npm run mainnet:certificate && npm run mainnet:certificate:validate. Validator reported: ${redactString(detail)}`}; } return {name:"Authorization gates",status:"PASS",value:certificate}; } catch(e:any) { return {name:"Authorization gates",status:"FAIL",value:certificate,nextAction:`Fix Mainnet authorization certificate. Validator reported: ${redactString(e.message)}`}; } }
async function doctor(networkName:string): Promise<{networkName:string; expected:number; detected?:number; checks:Check[]; allowedNextStep:string}> {
 loadDeploymentEnv(networkName); const expected=getExpectedChainId(networkName); const rpc=getOptionalRpcUrl(networkName); const key=getOptionalPrivateKey(networkName); const checks:Check[]=[];
 const main=networkName.includes("Mainnet");
 const noBroadcast=has("--no-broadcast")||has("--dry-run");
 checks.push({name:"RPC configured",status:rpc?"PASS":"FAIL",value:rpc?safeProviderName(rpc):"missing",nextAction:rpc?undefined:`Set ${networkName.includes("Mainnet")?"PRIVATE_MAINNET_RPC_URL":"PRIVATE_SEPOLIA_RPC_URL"}.`});
 checks.push({name:"Deployer key configured",status:key?/^0x[0-9a-fA-F]{64}$/.test(key)?"PASS":"FAIL":(main&&noBroadcast?"WARN":"FAIL"),value:key?"configured/redacted":(main&&noBroadcast?"not required for no-broadcast preflight":"missing"),nextAction:key?(/^0x[0-9a-fA-F]{64}$/.test(key)?undefined:"Use a 0x-prefixed 64-hex-character private key."):(main&&noBroadcast?"Final Mainnet broadcast still requires PRIVATE_MAINNET_DEPLOYER_PRIVATE_KEY locally.":`Set ${networkName.includes("Mainnet")?"PRIVATE_MAINNET_DEPLOYER_PRIVATE_KEY":"PRIVATE_SEPOLIA_DEPLOYER_PRIVATE_KEY"}.`)});
 let detected: number|undefined, addr="unavailable", bal="unavailable", nonce="unavailable";
 if(rpc){ try{ const provider=new ethers.JsonRpcProvider(rpc); detected=Number((await provider.getNetwork()).chainId); checks.push({name:"Chain ID detected",status:detected===expected?"PASS":"FAIL",value:String(detected),nextAction:detected===expected?undefined:`Fix RPC/network. Expected ${expected} for ${networkName}.`}); if(key && /^0x[0-9a-fA-F]{64}$/.test(key)){ const w=new ethers.Wallet(key,provider); addr=w.address; bal=ethers.formatEther(await provider.getBalance(addr)); nonce=String(await provider.getTransactionCount(addr)); const min=networkName.includes("Mainnet")?"0.50":"0.10"; checks.push({name:"Deployer balance",status:Number(bal)>=Number(min)?"PASS":"WARN",value:`${bal} ETH`,nextAction:Number(bal)>=Number(min)?undefined:`Fund deployer with at least about ${min} ETH before live broadcast.`}); }}catch(e:any){ checks.push({name:"Chain ID detected",status:"FAIL",value:"unavailable",nextAction:`Check RPC URL; provider error: ${e.message}`}); }}
 checks.push({name:"Deployer address",status:addr==="unavailable"?"WARN":"PASS",value:addr}); checks.push({name:"Nonce",status:nonce==="unavailable"?"WARN":"PASS",value:nonce}); checks.push({name:"Etherscan API configured",status:process.env.ETHERSCAN_API_KEY?"PASS":"WARN",value:process.env.ETHERSCAN_API_KEY?"configured/redacted":"missing",nextAction:process.env.ETHERSCAN_API_KEY?undefined:"Set ETHERSCAN_API_KEY before verify commands."});
 checks.push({name:"Compiler alignment",status:fs.existsSync("hardhat.config.ts")?"PASS":"FAIL",value:"Solidity 0.8.35 / Hardhat 2.28.6 expected"});
 checks.push({name:"Tests",status:"WARN",value:"not run by doctor",nextAction:"Run npm run test:ci before live deployment."});
 checks.push({name:"Static checks",status:"WARN",value:"not run by doctor",nextAction:"Run npm run static-check before live deployment."});
 const manifest=main?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json"; checks.push({name:"Deployment manifest",status:fs.existsSync(manifest)?"PASS":"WARN",value:manifest,nextAction:fs.existsSync(manifest)?undefined:`Run ${main?"npm run deploy:mainnet:live-local-gated":"npm run deploy:sepolia:live"} after readiness passes.`});
 const evidence=main?"qa/mainnet-deployment-evidence.json":"qa/sepolia-deployment-evidence.json"; checks.push({name:"Evidence files",status:fs.existsSync(evidence)?"PASS":"WARN",value:evidence,nextAction:fs.existsSync(evidence)?undefined:`Run ${main?"npm run deploy:mainnet:evidence":"npm run deploy:sepolia:evidence"}.`});
 const token=process.env.AGIALPHA_TOKEN_ADDRESS || (main ? "missing" : "not configured");
 checks.push({name:"AGIALPHA token",status:main?(token===AGIALPHA_MAINNET_TOKEN?"PASS":"FAIL"):(token==="not configured"?"WARN":"PASS"),value:token,nextAction:main?`Set AGIALPHA_TOKEN_ADDRESS=${AGIALPHA_MAINNET_TOKEN}.`:"Set AGIALPHA_TOKEN_ADDRESS before live deploy, or leave it blank only when the non-mainnet deployment path is intentionally allowed to deploy a fresh MockAGIALPHA."});
 checks.push({name:"Mock token used",status:main?(process.env.MOCK_AGIALPHA_ADDRESS?"FAIL":"PASS"):(process.env.MOCK_AGIALPHA_ADDRESS?"WARN":"PASS"),value:process.env.MOCK_AGIALPHA_ADDRESS?"configured/redacted":"false",nextAction:process.env.MOCK_AGIALPHA_ADDRESS?(main?"Unset MOCK_AGIALPHA_ADDRESS; MockAGIALPHA is forbidden on Mainnet.":"Confirm Sepolia mock-token rehearsal is intentional.") : undefined});
 checks.push({name:"New AGIALPHA token deployment",status:main&&String(process.env.DEPLOY_NEW_AGIALPHA_TOKEN).toLowerCase()==="true"?"FAIL":"PASS",value:String(process.env.DEPLOY_NEW_AGIALPHA_TOKEN||"false"),nextAction:main?"Unset DEPLOY_NEW_AGIALPHA_TOKEN; deploying a new AGIALPHA token is forbidden on Mainnet.":undefined});
 checks.push(main?mainnetAuthorizationGateCheck():{name:"Authorization gates",status:"PASS",value:"Sepolia operator authorization is environment-scoped"});
 if(main){ checks.push({name:"CI mainnet broadcast gate",status:noBroadcast?"PASS":((process.env.CI||process.env.GITHUB_ACTIONS)?"FAIL":"PASS"),value:noBroadcast?"CI-safe no-broadcast mode":((process.env.CI||process.env.GITHUB_ACTIONS)?"blocked in CI":"local shell"),nextAction:"Final Mainnet broadcast must be local-only."}); checks.push({name:"Typed confirmation",status:process.env.MAINNET_DEPLOYMENT_CONFIRMATION===CONFIRM?"PASS":"WARN",value:process.env.MAINNET_DEPLOYMENT_CONFIRMATION?"provided/redacted":"missing",nextAction:`Set MAINNET_DEPLOYMENT_CONFIRMATION=${CONFIRM} only for final local deploy.`}); }
 const fail=checks.find(c=>c.status==="FAIL"); return {networkName, expected, detected, checks, allowedNextStep: fail?`Fix: ${fail.nextAction}`:(main?"npm run deploy:mainnet:preflight":"npm run deploy:sepolia:dry-run")}; }
function print(d:any){ if(has("--json")) console.log(JSON.stringify(d,null,2)); else { console.log("\nGoalOS Deployment + Verification Command Center\n"); console.log(`Network: ${d.networkName}`); console.log(`Expected chainId: ${d.expected}`); console.log(`Detected chainId: ${d.detected ?? "unknown"}`); for(const c of d.checks){ console.log(`${renderStatus(c.status)} ${c.name}: ${c.value ?? ""}`); if(c.nextAction) console.log(`  Next action: ${c.nextAction}`);} console.log(`Allowed next step: ${d.allowedNextStep}`); }}
function writeMainnetPackage(){ fs.mkdirSync(".private",{recursive:true}); fs.writeFileSync(".private/mainnet-operator.env.template", fs.readFileSync(".env.mainnet.example")); fs.writeFileSync(".private/mainnet-final-command.txt", "source .private/mainnet-operator.env\nnpm run deploy:mainnet:live-local-gated\nnpm run verify:mainnet:all\nnpm run deploy:mainnet:evidence\n"); fs.writeFileSync(".private/mainnet-verification-command.txt", "source .private/mainnet-operator.env\nnpm run verify:mainnet:all\n"); fs.writeFileSync(".private/mainnet-post-deploy-evidence-checklist.md", `# Mainnet post-deploy evidence checklist\n\n- Confirm chainId=1 in the deployment manifest.\n- Confirm every tx hash is real and has code at the deployed address.\n- Run npm run verify:mainnet:all.\n- Run npm run deploy:mainnet:evidence only after real broadcast evidence exists.\n- Stop safely if any check fails; do not claim Mainnet deployed YES.\n`); fs.writeFileSync(".private/mainnet-operator-checklist.md", `# Mainnet local operator checklist\n\nDo not commit this directory. Fill .private/mainnet-operator.env from the template. Confirm MAINNET_TARGET=ethereum, AGIALPHA_TOKEN_ADDRESS=${AGIALPHA_MAINNET_TOKEN}, and type ${CONFIRM} only when ready. Ethereum Mainnet final broadcast is local-only and never CI.\n`); fs.writeFileSync(".private/mainnet-preflight-summary.redacted.json", JSON.stringify({generatedAt:new Date().toISOString(), mainnetDeployed:"NO", ciCanDeployMainnet:false, finalBroadcast:"local-only", agialphaToken:AGIALPHA_MAINNET_TOKEN, claimBoundary:CLAIM_BOUNDARY},null,2)+"\n"); console.log("Generated .private local operator package (redacted templates only)."); }

function resolveGrantAccount(g:any, policy:any): string {
 const raw=g.account;
 if(typeof raw==="string" && ethers.isAddress(raw)) return ethers.getAddress(raw);
 if(g.accountRedacted && raw?.commitmentHash){
  const candidates=[policy?.operationsAddress, policy?.governanceOwner, policy?.treasuryAddress, ...Object.values(policy?.vaultOwners||{})].filter(Boolean).map(String);
  const match=candidates.find((value)=>ethers.isAddress(value) && shaText(ethers.getAddress(value).toLowerCase())===String(raw.commitmentHash));
  if(match) return ethers.getAddress(match);
  throw new Error("Redacted Phase-B grantee requires --policy with matching operations/governance/treasury/vault address");
 }
 throw new Error(`Invalid Phase-B grantee for ${g.label||g.target}`);
}
function prepareSafeConfiguration(networkName:string){
 const main=networkName.includes("Mainnet");
 const manifest=main?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json";
 if(!fs.existsSync(manifest)) throw new Error(`Missing deployment manifest ${manifest}`);
 const m=JSON.parse(fs.readFileSync(manifest,"utf8"));
 const grants=Array.isArray(m.phaseBGrants)?m.phaseBGrants:[];
 if(!grants.length) throw new Error("No phaseBGrants found in deployment manifest");
 const policy=readAuthorityPolicy();
 const iface=new ethers.Interface(["function grantRole(bytes32 role,address account)"]);
 const transactions=grants.map((g:any,i:number)=>{ const grantee=resolveGrantAccount(g,policy); const data=iface.encodeFunctionData("grantRole",[g.role,grantee]); return {id:i+1,to:ethers.getAddress(g.target),value:"0",data,contractMethod:{name:"grantRole",payable:false,inputs:[{name:"role",type:"bytes32"},{name:"account",type:"address"}]},contractInputsValues:{role:g.role,account:grantee},method:g.method||"grantRole(bytes32,address)",role:g.role,grantee,rationale:g.label}; });
 const out={schemaVersion:1, networkName, chainId:m.chainId, safe:m.governanceOwner||policy?.governanceOwner||m.governanceOwnerCommitmentHash||"redacted-governance-owner", createdAt:new Date().toISOString(), transactions, transactionCount:transactions.length, batchHash:shaText(JSON.stringify(transactions)), claimBoundary:"Safe Transaction Builder preparation only; executable calldata is generated locally and no transaction is submitted or broadcast."};
 fs.mkdirSync(".private",{recursive:true});
 const outPath=main?".private/mainnet-safe-configuration-plan.json":".private/sepolia-safe-configuration-plan.json";
 fs.writeFileSync(outPath,JSON.stringify(out,null,2)+"\n");
 console.log(`Wrote ${outPath} with ${grants.length} executable Phase-B grant calls`);
}

async function verifySafeConfiguration(networkName:string){
 const main=networkName.includes("Mainnet");
 const manifest=main?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json";
 if(!fs.existsSync(manifest)) throw new Error(`Missing deployment manifest ${manifest}`);
 const rpc=getOptionalRpcUrl(networkName);
 if(!rpc) throw new Error(`Missing RPC URL for ${networkName} configuration verification`);
 const provider=new ethers.JsonRpcProvider(rpc);
 const expectedChainId=getExpectedChainId(networkName);
 const detectedChainId=Number((await provider.getNetwork()).chainId);
 if(detectedChainId!==expectedChainId) throw new Error(`Configuration verification RPC chainId mismatch: expected ${expectedChainId} for ${networkName}, got ${detectedChainId}`);
 const m=JSON.parse(fs.readFileSync(manifest,"utf8"));
 if(Number(m.chainId)!==expectedChainId) throw new Error(`Deployment manifest chainId mismatch: expected ${expectedChainId}, got ${m.chainId}`);
 const grants=Array.isArray(m.phaseBGrants)?m.phaseBGrants:[];
 if(!grants.length) throw new Error("No phaseBGrants found in deployment manifest");
 const policy=readAuthorityPolicy();
 const abi=["function hasRole(bytes32 role,address account) view returns (bool)"];
 const results=[];
 for(const g of grants){ const grantee=resolveGrantAccount(g,policy); const c=new ethers.Contract(ethers.getAddress(g.target),abi,provider); const ok=await c.hasRole(g.role,grantee); const redacted=Boolean(g.accountRedacted); results.push({target:ethers.getAddress(g.target),role:g.role,grantee:redacted?"redacted":grantee,granteeCommitmentHash:redacted?g.account?.commitmentHash:undefined,label:g.label,ok}); }
 const failed=results.filter((r)=>!r.ok);
 const out={schemaVersion:1,status:failed.length?"FAILED":"PASSED",networkName,chainId:detectedChainId,manifestChainId:m.chainId,checkedAt:new Date().toISOString(),deploymentManifest:manifest,grantCount:results.length,results,claimBoundary:"Phase-B configuration role check only; no transaction is broadcast; redacted grantees remain commitment-only in public QA output."};
 fs.mkdirSync("qa",{recursive:true}); const outPath=main?"qa/mainnet-configuration-verification.json":"qa/sepolia-configuration-verification.json"; fs.writeFileSync(outPath,JSON.stringify(out,null,2)+"\n");
 if(failed.length) throw new Error(`Phase-B configuration verification failed for ${failed.length} grants`);
 console.log(`PASS wrote ${outPath} with ${results.length} verified grants`);
}
function evidence(networkName:string){ const main=networkName.includes("Mainnet"); const manifest=main?"deployments/ethereum-mainnet.agialpha.latest.json":"deployments/ethereum-sepolia.agialpha.latest.json"; if(main && !fs.existsSync(manifest)) throw new Error("Mainnet evidence blocked: no real chainId=1 deployment manifest exists. Mainnet deployed remains NO."); const m=fs.existsSync(manifest)?JSON.parse(fs.readFileSync(manifest,"utf8")):{network:"ethereum-sepolia",chainId:11155111,contracts:{},transactions:[],verificationStatus:"NOT_RUN"}; const txHashes=manifestTransactionHashes(m); const hash=fs.existsSync(manifest)?shaFile(manifest):"manifest-not-yet-generated"; if(fs.existsSync(manifest)) fs.writeFileSync(manifest.replace(/\.json$/, ".sha256"), hash+"\n"); const out={networkName:m.network||networkName,chainId:m.chainId, deployerPublicAddress: main ? (m.deployerCommitmentHash?"commitment:"+m.deployerCommitmentHash:String(m.deployer||"redacted-or-not-yet-deployed")) : "public-deployer-recorded-in-manifest", rpcProviderName:safeProviderName(getOptionalRpcUrl(networkName)), timestamp:new Date().toISOString(), gitCommit:process.env.GITHUB_SHA||"local", packageVersion:JSON.parse(fs.readFileSync("package.json","utf8")).version, solidityCompilerVersion:"0.8.35", hardhatVersion:"2.28.6", agialphaTokenAddress: main ? (m.agialphaToken||AGIALPHA_MAINNET_TOKEN) : "public-token-recorded-in-manifest", mockTokenUsed:!!m.mockAgialphaUsed, newAgialphaTokenDeployed:!!m.newAgialphaTokenDeployed, deployedContractAddresses: main ? (m.contracts||{}) : Object.fromEntries(Object.keys(m.contracts||{}).map((name)=>[name,"public-address-recorded-in-manifest"])), transactionHashes: main ? txHashes : txHashes.map(()=>"public-transaction-hash-recorded-in-manifest"), gasUsedOrEstimated:m.gasUsed||m.estimatedGas||"not recorded", verificationStatus:m.verificationStatus||"NOT_RUN", manifestHash:hash, postDeploymentChecks:[], claimBoundary:CLAIM_BOUNDARY, nextRecommendedAction: main?"Run npm run deploy:mainnet:verify after real local broadcast.":"Run npm run deploy:sepolia:verify if not already verified."}; fs.mkdirSync("qa",{recursive:true}); fs.mkdirSync("docs",{recursive:true}); const q=main?"qa/mainnet-deployment-evidence.json":"qa/sepolia-deployment-evidence.json"; const r=main?"docs/ETHEREUM_MAINNET_DEPLOYMENT_REPORT.md":"docs/SEPOLIA_DEPLOYMENT_REPORT.md"; fs.writeFileSync(q,JSON.stringify(out,null,2)+"\n"); fs.writeFileSync(r,`# ${main?"Ethereum Mainnet":"Sepolia"} Deployment Report\n\nMainnet deployed: ${main?"NO unless this report was generated from a real chainId=1 manifest with transactions":"N/A"}\n\nManifest hash: ${hash}\n\nClaim boundary: ${CLAIM_BOUNDARY}\n`); console.log(`Wrote ${q} and ${r}`); }
async function main(){ const action=process.argv[2]||"doctor"; const networkName=networkFromArgs(action); loadDeploymentEnv(networkName); if(action.includes("configure-verify")){await verifySafeConfiguration(networkName);return;} if(action.includes("prepare-safe")){prepareSafeConfiguration(networkName);return;} if(action.includes("prepare-local")){writeMainnetPackage();return;} if(action.includes("evidence")){evidence(networkName);return;} if(action.includes("status")||action.includes("next")||action.includes("doctor")||action.includes("preflight")||action.includes("dry-run")||action.includes("fork-rehearsal")){ const result=await doctor(networkName); print(result); if(result.checks.some((check)=>check.status==="FAIL")) process.exitCode=1; return;} throw new Error(`Unknown command-center action: ${action}`); }
main().catch(e=>{console.error(e.message||e);process.exitCode=1});
